### ISSUE TITLE
It i possible iris or shield for gate? It could be better.

### ISSUE THREAD

**Issue by rokyscz** [PC-Logix/LanteaCraft#124]

**Comment by hehe3301** [comment]
As a clarification: When the iris is implemented will the GDO be implemented as well?

**Comment by hehe3301** [comment]
Second Clarification: Will Milky-way gates have iris and Pegasus gates have a shield?

**Comment by Cronosus** [comment]
i think, two items: energy iris and mechanical iris, you can use both on any gate (only one at gate).
gdo is for deactivating iris.. then yes

**Comment by AfterLifeLochie** [comment]
Implemented as of f361f84d32bfa446fc10e915140ef2c7c5bd7f56.
