### ISSUE TITLE
DHD behaves like dialing computer

### ISSUE THREAD

**Issue by hunator** [PC-Logix/LanteaCraft#164]
In series, when dialing gate through DHD gate just lids chevrons and makes sound. Spinning of inner ring is just for manual dial-up (by hand or dialing computer).

I know that it has got some glitches because no time delay between entering one gate and exiting another one. This glitches were also in series. Like where someone is dialing your gate really slow and you are still able to dial different address. It is wrong because network needs to know which gate to dial. So activation of receiving gate has to be instant after last symbol on transmitting gate has been dialed.

In Carter addon pack for Gary's Mod, it seams to be solved. I've found video on youtube which shows it.
http://www.youtube.com/watch?v=avru2Q_jka4

I know that it is not top priority issue, but just to track that it should behave differently for computer and DHD.

**Comment by AfterLifeLochie** [comment]
This is now implemented as of `LC2-5`.
