### ISSUE TITLE
numbers in address won't work

### ISSUE THREAD

**Issue by ToddVee** [PC-Logix/LanteaCraft#207]
it seems the numbers don't work with RC-48

click on "9" makes the gate dial "0"
click on "8" and the gate dials "9"
...
click on "5" or "4", the gate dials "4"

gates without numbers in the address work fine.

**Comment by AfterLifeLochie** [comment]
Can I please get confirmation that this issue still exists in LC2? I've rewritten huge chunks of the DHD handling, and I'd like to confirm that this is still a problem.

**Comment by AfterLifeLochie** [comment]
I'm assuming this is resolved due to no response from the submitter.
