### ISSUE TITLE
Suggestion: Improve Addressing System

### ISSUE THREAD

**Issue by Sarous** [PC-Logix/LanteaCraft#237]
The LanteaCraft homepage stated a range on 877,936 block (54,871 chunk) range on its addressing system. As this mod also states that it is based off of Greg's SGCraft, I think it might be useful to point out that in current SGCraft builds it has an approx range of 2,239,466 blocks (139966 chunks), using alpha-numeric addressing (without plus & minus symbols).

Additionally, I'd like to point out a crash-bug when checking a gate's address while out of addressing range, and a related crash-bug when trying to dial out from an out-of-range gate.

**Comment by AfterLifeLochie** [comment]
This is now resolved via the new addressing engine in LC2. It is no longer possible to run out of addresses, and addresses don't have index issues or lots of repeated characters.
