### ISSUE TITLE
7 Chervron

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#242]
if you dial with a seven chevron address dials chevron 1,2,3,6,7,8,4 and not the top(9)

to make the nummbers clear:
R8R9R1R
REEEEER
7EEEEE2
REEEEER
REEEEER
6EEEEE3
R5RBR4R

R = ringblock
B = base 
E = epmpty space
i hope this is clear

**Comment by lieven121** [comment]
isnt this fixed now ???

**Comment by AfterLifeLochie** [comment]
As far as I'm aware, this has been fixed in LC2-series rendering changes.
