### ISSUE TITLE
breaking of the gate 

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#249]
If you break a gate you still can dial to that gate + no explosions ?? (It can be for testing/stability reasons its turned off like ic2)

**Comment by AfterLifeLochie** [comment]
Is the first part of this issue still a problem in current versions?

**Comment by iTimmyLP** [comment]
I use the latest version and yes, if you place in the gate, that this is deforms ( i know, this is a part of LC ) but if you dial, you always can hear the gate dialing, but nothing more will happen

**Comment by lieven121** [comment]
srr I didn't see this reply a long time ago and didn't see it til now the breaking of the gate makes it unable to dial / to dial to other gates so this is fixed and explosions if a is blown up /gate is active and gets broken maybe in the future but that's not necessary for now so I consider it closed

**Comment by lieven121** [comment]
can anyone tell me how to close it or just close it because I forgot
