### ISSUE TITLE
Power issues

### ISSUE THREAD

**Issue by JasonMcRay** [PC-Logix/LanteaCraft#254]
If using RF power to power DHD:
When I get DHD to 100% with RF energy it will never go down (will never use power).
If I get less than 100% in the DHD it will be dropping down. But even when the power in DHD reaches 0 the gate will still be opened. When the gate closes (either manually or automaticaly) I can still dial adresses and walk through the gate and get transported without issues even when the energy in DHD is 0.

If using EU power to power DHD:
When DHD is at 100% with EU energy it will go down without a problem (is using power)
The second problem still remains. I can dial the adress and open the gate even when DHD is at 0% after its discharged.

Another issue:
DHD will get power only when I power it with minimum of 8200RF/t. But its using only 3RF/t. Also after DHD is full its still draining the RF from the RF energy storage.

With trying to use EU it is powering fine and when DHD is full on power (100%) the power is no longer drained from EU energy storage.

If needed more info, I will try to provide as much as I can.

Using Lanteacraft: 1.7.10-52
MC: 1.7.10
Forge: 10.13.2.1232

**Comment by Cronosus** [comment]
i have similar problem, i test with IC and Themal too
when is energy on dhd 0 gate opened and closed immediately (not enought energy), but when i connect EU or RF and fill dhd to 100%, i can normally open gate, bud gate not consume energy from dhd, dhd is still at 100% without any energy source.
