### ISSUE TITLE
Gates indestructible and strange behaviour

### ISSUE THREAD

**Issue by DrStage** [PC-Logix/LanteaCraft#256]
I've noticed that the gateblocks are quite durable...or better nearly indestructible. I've tested TNT, Mekanism Obsidian TNT and finally an IC2 Nuke (with Plutonium), the gate didn't care.

Same as #249: breaking the gate does not produce an explosion. Furthermore it is still possible to dial with a broken gate and use it like an intact one.

http://imgur.com/qV3fvsF (the gate on the left is connected to the broken one).

Another thing I found: placing a block within the gate will deform it, but it still continues to work like normal.
http://imgur.com/9AxNxe6

(Don't know if I should open a new issue, so I write it here first)
Feature request: I've seen that SG Craft adds the possibility to camouflage the stargate base. This would be a nice addition for LanteaCraft 2!

**Comment by Gunner76th** [comment]
re: Feature request: I've seen that SG Craft adds the possibility to camouflage the stargate base. This would be a nice addition for LanteaCraft 2!

Personally I do not approve of this idea. I cannot remember ever there being a time in which any stargate, Wraith, Pegasus, Milky Way, or other was ever camouflaged so as to be hidden. Covered in overgrowth or buried yes, but a functioning stargate that looked like its surroundings (AKA sand or dirt) I can not recall this ever being a thing.

**Comment by AfterLifeLochie** [comment]
This isn't talking about camouflaging the whole Stargate, this is about sitting the Stargate flush with the floor or ceiling which was a common appearance in all of the shows.

**Comment by lieven121** [comment]
I think this issue is solved to (except for the explosion part)
