### ISSUE TITLE
Multiblock breaks and DHD link also broken

### ISSUE THREAD

**Issue by BBtraceur** [PC-Logix/LanteaCraft#269]
Hi there,

First off great mod! can't see myself playing without it. 

Was playing this afternoon on my private server and the gate wasnt round anymore. DHD link was also down. I destroyed the base block and place a new one and recreated the gate. My only guess was this was due to server restart. (server has just been created and has been running for 3 days).

Went playing normally again walked a pretty good distance from the gate (+250 blocks). When I got back the gate was broken again. so I don't think server restart had anything to do with it.

Only thing I changed is the allocated ram to the server in the.bat file but can't see this has anything to do with it.

I can't really troubleshoot since I don't know where to look
I tried finding this issue here to no avail. 

Hope anyone can help.

-B

**Comment by BBtraceur** [comment]
![2015-01-01_21 16 05](https://cloud.githubusercontent.com/assets/10343864/5593172/80582444-91fb-11e4-9f5a-4a076375c0f2.png)

Same issue but, this time partially?
link with DHD is still intact and gate connection can be established

**Comment by MichiyoRavencroft** [comment]
That's not the same issue.  That issue is because the left and right half of the gate are in different chunks. It's a known possibly semi related issue, but not the issue discussed here.

**Comment by BBtraceur** [comment]
ok IC. When moving through and back to the gate (dimension) it was fixed. the original problem still persists. disregard last post

**Comment by BBtraceur** [comment]
I found a temp. fix. When the problem occurs, relogging fixes the gate and resets the link with the DHD. Something client side, maybe?

**Comment by AfterLifeLochie** [comment]
This has been fixed in a future version. In the meantime, you can either place an explicit chunkloader on the gate, or move it such that it fits entirely in one chunk.
