### ISSUE TITLE
Gates won't work underwater

### ISSUE THREAD

**Issue by iTimmyLP** [PC-Logix/LanteaCraft#273]
http://www11.pic-upload.de/01.01.15/a5bx3uscpkvo.png

The Gates do not work underwater. I think the problem is, that the "waterblocks" are detected as block and the Gate will deform.

MC: 1.7.10
LC: 1.7.10-63
Forge: 10.13.2.1277

**Comment by Kodos-Atoz** [comment]
That's because flowing water is still a block, and will deform the gate.  And I don't see this being fixed, as this is a core Minecraft mechanic.

**Comment by iTimmyLP** [comment]
what is about with an exception for this blockID?

**Comment by morlanius** [comment]
and allow flowing water to spawn through the gate ;) lets see someone open to an underwater gate and flood their SGC.

**Comment by dominikh** [comment]
@morlanius The gate can block fluids/detect that they don't actually want to pass through, due to the pressure exerted :P

**Comment by morlanius** [comment]
i was just finding the concept of an underwater gate interesting. gating to lava would be interesting.

**Comment by AfterLifeLochie** [comment]
You couldn't dial an underwater gate and become flooded as a result. Only radio-signals have ever passed in reverse through a Stargate.

Minecraft's fluid mechanics are a pain to work with, so I highly doubt I'll add flooding as a feature.

**Comment by iTimmyLP** [comment]
In the one Episode of SG1 the Russians has a gate and travel to an "Underwater"-Planet. 
I know that the "Water" is a form of living, but the earth side doesn't get flooded.

**Comment by AfterLifeLochie** [comment]
They make an *outgoing* connection to the underwater gate. The water can't back-flow through the Stargate because that's not the direction of travel.

**Comment by iTimmyLP** [comment]
That is that i already now, but they travel back to Earth without flood the russians "SGC"

**Comment by Kodos-Atoz** [comment]
I have no idea what you just said, but given that the original purpose of this issue has already been addressed...

**Comment by AfterLifeLochie** [comment]
I genuinely don't think I need to support Stargates working underwater. It just doesn't make much sense in the long run.
