### ISSUE TITLE
Gate without an Address and not dialable

### ISSUE THREAD

**Issue by iTimmyLP** [PC-Logix/LanteaCraft#276]
![2015-01-05_15 30 47](https://cloud.githubusercontent.com/assets/6671741/5614469/f25fc4f4-94f1-11e4-80a9-47324b93858f.png)
![2015-01-05_15 29 19](https://cloud.githubusercontent.com/assets/6671741/5614471/f2fd54a8-94f1-11e4-8360-0a341c2c7bf1.png)
This gate dont have an address and cant dial out.
Try rightclick and try to dial will crash the Game.

**Comment by MichiyoRavencroft** [comment]
Crash log?

**Comment by AfterLifeLochie** [comment]
You're actually probably beyond the maximum we can store in an address (chunk 18749).

Fixed in future versions.
