### ISSUE TITLE
Disconnect when gate is connecting results in a server crash !

### ISSUE THREAD

**Issue by Yuri6037** [PC-Logix/LanteaCraft#278]
Hello,

I'm hosting a cauldron server, i know that this can be buggy, and i'd understand if you won't solve this issue, but i hope you'll just try to understand what can cause the issue...

So i made a ComputerCraft program to command the Stargate, and everything works fine except when i try to force disconnect the stargate while it's composing to another stargate. Indead, the server crashes with a strange exception (I'm Java programmer, and i never had this exception)...

It seams to be a CraftBukkit error but i'm not sure.

---- Minecraft Crash Report ----
// Why did you do that?

Time: 09/01/15 14:16
Description: Exception ticking world

java.util.NoSuchElementException
	at org.bukkit.craftbukkit.v1_7_R4.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:346)
	at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.processChunkGC(CraftWorld.java:1392)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:301)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at org.bukkit.craftbukkit.v1_7_R4.util.LongObjectHashMap$ValueIterator.next(LongObjectHashMap.java:346)
	at org.bukkit.craftbukkit.v1_7_R4.CraftWorld.processChunkGC(CraftWorld.java:1392)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:301)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['Yuri6037'/317, l='world', x=1247,75, y=19,00, z=-78,39](Yuri6037 at 1247.752943714104,19.0,-78.38724462686659)]
	Chunk stats: ServerChunkCache: 763 Drop: 47
	Level seed: -8688013121198245577
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (228,64,224), Chunk: (at 4,4,0 in 14,14; contains blocks 224,0,224 to 239,255,239), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 723501 game time, 736570 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 6766 (now: true), thunder time: 76666 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:920)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.7.0_45, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 231881984 bytes (221 MB) / 1203765248 bytes (1148 MB) up to 3937402880 bytes (3755 MB)
	JVM Flags: 2 total; -Xmn1024m -Xmx4096m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 3, tcache: 32, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.25.1207 Minecraft Forge 10.13.0.1207 23 mods loaded, 23 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.25.1207} [Forge Mod Loader] (cauldron-1.7.10-1.1207.01.198-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.0.1207} [Minecraft Forge] (cauldron-1.7.10-1.1207.01.198-server.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	LanteaCraft-Core{1.0} [LanteaCraft Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	PlayerAPI{1.1} [Player API] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SmartCore{1.0} [Smart Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	doggytalents{v1.7.3a} [Doggy Talents] ([1.7.10] Doggy Talents - v1.7.3a.zip) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	extrastairs{1.7.10-2.0} [extrastairs] ([1.7.10]ExtraStairs.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AncientAddin{InDev} [AncientAddin Mod] (AncientAddin-InDev.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ArchimedesShips{1.7.10 v1.7.1} [Archimedes' Ships] (ArchimedesShips-1.7.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ComputerCraft{1.65} [ComputerCraft] (ComputerCraft1.65.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SlimevoidLib{2.0.4.6} [Slimevoid Library] (SlimevoidLibrary-2.0.4.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	DynamicTransport{0.1.2.0} [Dynamic Transport] (DynamicTransport-0.1.2.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	LanteaCraft{1.0.0-63} [LanteaCraft] (LanteaCraft-1.7.10-63.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MrTJPCoreMod{1.0} [MrTJPCoreMod] (MrTJPCore-1.7.10-1.0.3.5-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.0.314} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Core{4.5.6.57} [ProjectRed] (ProjectRed-1.7.10-4.5.6.57-Base.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Integration{4.5.6.57} [ProjectRed-Integration] (ProjectRed-1.7.10-4.5.6.57-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ProjRed|Transmission{4.5.6.57} [ProjectRed-Transmission] (ProjectRed-1.7.10-4.5.6.57-Integration.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SmartMoving{15.2} [Smart Moving] (SmartMoving-1.7.10-15.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	SpecialArmor{1.7.10} [TeeLuk's SpecialArmor] (TLSpecialArmor-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.0.314} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.0.314} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.0.314-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 20; [EntityPlayerMP['Yuri6037'/317, l='world', x=1247,75, y=19,00, z=-78,39](Yuri6037 at 1247.752943714104,19.0,-78.38724462686659)]
	Is Modded: Definitely; Server brand changed to 'cauldron,craftbukkit,mcpc,fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Gunner76th** [comment]
Can you reproduce this same error in a pure forge enviroment? AFAIK there are no mod authors that will service any crashes for any reason that occur with a Cauldron server, because of 2 reasons 1: Cauldron and all things Bukkit are under a DCMA takedown order, which means there will be no support or work for Cauldron or Bukkit 2: the methods in which Cauldron deals with the code so that it can play with both forge mods and bukkit plugins is such that, it will toss errors and create crashes when a normal forge server would not. 

With this being said, I suggest you try to recreate this crash report sing only forge and forge based mods, and if the issue is still present, then it will more than likely be considered a valid crash.

**Comment by AfterLifeLochie** [comment]
This is a known issue with Cauldron and Bukkit servers.

It's certainly still possible to get and work with Cauldron and Bukkit to this day.

**Comment by AfterLifeLochie** [comment]
This bug will not be fixed as LC2 builds are now promoted to release in order to replace these buggy ones.
