### ISSUE TITLE
LanteaCraft crashes without supporting power API

### ISSUE THREAD

**Issue by domilink1945** [PC-Logix/LanteaCraft#280]
When i download Lanteacraft and install it and then open minecraft, minecraft crashes what do i need to do????

**Comment by lyqyd** [comment]
Please provide the crashlog by copying and pasting it to something like pastebin.com, then providing the link here.

**Comment by domilink1945** [comment]
The link to pastebin is http://pastebin.com/1iYp9bRq

**Comment by mRichard629** [comment]
I'm getting issues with 1.7.10-67. Every time I launch MC it crashes. at first I assumed it was just Mod Conflicts, so I dumped everything else seeing as LC is the only real mod I use. It still continued to crash, so I re-added the other few mods i use, and copied the error. 

http://pastebin.com/EcpX7UZk

I apologize if this is considered thread jacking, it just seemed similar to my issue and I didn't want to spam by adding a second thread with the same issue

**Comment by domilink1945** [comment]
mRichard629 Reinstall forge that did help me out

**Comment by mRichard629** [comment]
tried, still nothing

**Comment by MichiyoRavencroft** [comment]
The issue is in our class transformer, you have no power mods and our transformer is supposed to remove references to the powered tile entities, but it isn't.. As a test, please grab CofHCore/CofHLib and try to launch the game with them installed.

**Comment by mRichard629** [comment]
Problem solved by adding Cofh mods

**Comment by MichiyoRavencroft** [comment]
Yeah I figured that was the issue, we'll have to go over the Class Transformer and figure out what the issue is.  Thanks for the report.  @domilink1945 try the above solution and see if it works please.
