### ISSUE TITLE
events do not work in OpenComputers

### ISSUE THREAD

**Issue by iTimmyLP** [PC-Logix/LanteaCraft#283]
i have tried a long time to use this events but no one works for me.
sgIncoming
sgOutgoing
sgIdle
sgChevronEncode
sgWormholeOpening
sgWormholeClosing
sgWormholeStable

i use the latest OC and LC versions

**Comment by Kodos-Atoz** [comment]
Can you pastebin your code? I'll see what I can figure out.

**Comment by iTimmyLP** [comment]
not really... 
in rage i have delete the complete world...

**Comment by Kodos-Atoz** [comment]
Then please close the issue =)  If you have any issues again, please message me on IRC.  You can contact me in either #LanteaCraft or via PM, my name on IRC is 'Kodos'
