### ISSUE TITLE
Method returns "function"?!?

### ISSUE THREAD

**Issue by iTimmyLP** [PC-Logix/LanteaCraft#284]
The picture is selfexplaining:
![Returning](http://puu.sh/eFwpR/8b8d9baa3f.jpg)

**Comment by MichiyoRavencroft** [comment]
http://puu.sh/eFxlP/c82378d707.jpg

**Comment by AfterLifeLochie** [comment]
Please confirm with me before opening issues further on the tracker. So far, these have not been issues at all. I would strongly recommend you read a guide on Lua 5.1 before continuing.

I will not hesitate to block you if you continue to open issues which are not actually issues, particuarly when they are not even related to our code.

**Comment by MichiyoRavencroft** [comment]
Just a note, OC is Lua 5.2, though it wont make a huge difference.

**Comment by AfterLifeLochie** [comment]
It does not matter; the difference between Lua 5.1 and 5.2 lexically and statically is the addition of GOTO and the label feature.
