### ISSUE TITLE
Suggestion: new Event for OC/CC sgDialingStopped

### ISSUE THREAD

**Issue by iTimmyLP** [PC-Logix/LanteaCraft#286]
sgDialingStopped: 
 - will be triggerd when to try to dial a gate, whitch allready have an established wormhole
or
 - will be triggerd when you hit the orange button while dialing.

**Comment by AfterLifeLochie** [comment]
My understanding is that this is already possible given the events we have, either through listening to the events themselves or waiting for a duration before giving up (given that dialling always takes a constant time). Could @CaitlynMainer comment please?

**Comment by CaitlynMainer** [comment]
I could have swore I replied to this.. It might have been a similar thing on the MCF post... 
1.) just check the gate's status before you send a dial via "isConnected" and "isDialing".
2.) Watch the sgIdle event and keeping track of the state if you switch from sgOutgoing to sgIdle without seeing a sgWormholeOpening, or sgWormholeStable event then the dialing was stopped for some reason.
