### ISSUE TITLE
Gates are not using power

### ISSUE THREAD

**Issue by Sarous** [PC-Logix/LanteaCraft#290]
Been suspecting this bug while using IC2 power sources for several builds now, and finally confirmed while using a ZPM last night- They drain power initially (but only about .0..0422% entropy, compared to the .0..01022% that it did several releases ago) and does not increase entropy after several dialings.

1.7.10
LanteaCraft v68

**Comment by AfterLifeLochie** [comment]
I disabled power use because there are problems with the CoFH API and all sorts of other IC2 related issues.
