### ISSUE TITLE
How i can add the ores to Dense Ores

### ISSUE THREAD

**Issue by iTimmyLP** [PC-Logix/LanteaCraft#294]
i have tried to add the ores to "Dense Ores" config like this:
    block_57 {
        S:baseBlock=LanteaCraft:tile.lanteaOre.0
        I:baseBlockMeta=0
        S:baseBlockTexture=LanteaCraft:tile.lanteaOre.0
        D:denseOreProbability=1
        I:renderType=1
        I:retroGenID=1
        S:underlyingBlock=stone
    }

    block_58 {
        S:baseBlock=LanteaCraft:tile.lanteaOre.2
        I:baseBlockMeta=0
        S:baseBlockTexture=LanteaCraft:tile.lanteaOre.2
        D:denseOreProbability=1
        I:renderType=1
        I:retroGenID=1
        S:underlyingBlock=stone
    }

    block_59 {
        S:baseBlock=LanteaCraft:tile.lanteaOre.2
        I:baseBlockMeta=0
        S:baseBlockTexture=LanteaCraft:tile.lanteaOre.2
        D:denseOreProbability=1
        I:renderType=1
        I:retroGenID=1
        S:underlyingBlock=stone
    }

Successless

for example the certus quartz ore from AE2
    block_55 {
        S:baseBlock=appliedenergistics2:tile.OreQuartz
        I:baseBlockMeta=0
        S:baseBlockTexture=appliedenergistics2:OreQuartz
        D:denseOreProbability=1
        I:renderType=1
        I:retroGenID=1
        S:underlyingBlock=stone
    }

Works without problems.

Can you help me, please?

**Comment by AfterLifeLochie** [comment]
`LanteaCraft:tile.lanteaOre.2` isn't a thing. You need to set the metadata instead. The block is `lanteaOre`.

Also, this would have been better suited on MCF.

**Comment by iTimmyLP** [comment]
I cant get it to work with LanteaCraft:lanteaOre

**Comment by Kodos-Atoz** [comment]
Why not just make a post on the MCF thread, as suggested?
