### ISSUE TITLE
Compatability

### ISSUE THREAD

**Issue by Tyrantin** [PC-Logix/LanteaCraft#297]
I their any conflicts with other mods at this time? I really would like to use this in my future mod pack/Server!

**Comment by AfterLifeLochie** [comment]
No. There are no conflicts,  else we'd list them on our site and the MCF post.

Do not use the issue tracker as a question board; issue trackers are for tracking problems or suggestions in our code. Ask on the MCF thread and someone will answer.

If you do this again, I am liable to remove your rights to see or contribute to the issue tracker permanently.
