### ISSUE TITLE
Compatability

### ISSUE THREAD

**Issue by Tyrantin** [PC-Logix/LanteaCraft#298]
Is it in the works to integrate Lantea with other mods so they can work together!

**Comment by MichiyoRavencroft** [comment]
If you wish to ask questions please use the Minecraft Forums thread, or the forums at http://lanteacraft.com/community/  This is not a place to ask questions.

**Comment by hehe3301** [comment]
I love seeing this email thread: 957 question, 958 this is not a place for
a question, 959 closed.
