### ISSUE TITLE
Item Stacking Issues

### ISSUE THREAD

**Issue by Zunth5** [PC-Logix/LanteaCraft#301]
LC-1.7.10-68

Shift click crafting Trinium ingots (with iron and Trinium) while having an incomplete stack of Naquadah ingots in inventory will convert Trinium to and fill into the Naquadah stack. I believe this works going in the opposite direction from Naquadah to Trinium. Correct me if im wrong, but I dont believe this was fixed in LC-1.7.10-69.

**Comment by AfterLifeLochie** [comment]
I might be a little bit stupid, but can you explain this in a step-by-step for me and explain exactly what output you see versus what you expect? Written narratives are not helping me much at the moment.

**Comment by Zunth5** [comment]
No problem, I know i can be a bit technical and dry.

1-Put some crafted trinium ingots in inventory. Not a full stack.

2-Put raw Naquadah and iron in a crafting table.

3-Try to shift click naquadah ingots out of the crafting table (normally just moves them into stacks in inventory) 

4-profit

These convert into and fill the trinium ingots stack, but you should be getting a separate naquadah stack.

**Comment by Zunth5** [comment]
Well...     accidentally just shift clicked my Trinium from my inventory into Naquadah in a chest. 

So its not the crafting process that is the issue. Its when shift click moving naquadah or Trinium to an a location with the opposite already there that the item stack convert and combine.

**Comment by AfterLifeLochie** [comment]
Okay, thanks. I'm a bit sick at the moment so this makes more sense to me.

Are you using inventory tweaks or anything extra which modifies the behaviour of shift-clicking, etc?

**Comment by AfterLifeLochie** [comment]
Nope, found the bug. Fixed, will be in a patch build now.

**Comment by Zunth5** [comment]
Thanks Lochie,

Your the best and I hope that you get well soon.

**Comment by AfterLifeLochie** [comment]
Grab 1.7.10-b70. It fixes the issue.
