### ISSUE TITLE
Compile GitHub Source from LC. I Can't read Crashlogs D:

### ISSUE THREAD

**Issue by iTimmyLP** [PC-Logix/LanteaCraft#302]
I have just compiled the source from here.
What i do wrong?

http://pastebin.com/1cD6HfdL

**Comment by CaitlynMainer** [comment]
I've stated a few times we do not support self built jars... but from the look of it you're building the wrong branch.  https://github.com/PC-Logix/LanteaCraft/tree/1.7.10-legacy-patches  This will be the only support I will offer on the subject.

**Comment by AfterLifeLochie** [comment]
We do not support building your own JAR files and we never will. You will be unable to make a functional JAR file without the use of our Jenkins service, also.
