### ISSUE TITLE
Instant break of blocks  (build 70, unstable 16)

### ISSUE THREAD

**Issue by Cronosus** [PC-Logix/LanteaCraft#303]
Hello
i can destroy instantly:
<strike>-decor blocks (all)</strike>
-braziers (all)
-transporter ring (block)
-obelisks (all)
-doors (both)
-configurator (notebook)

missing setHardness(); in code

**Comment by AfterLifeLochie** [comment]
I don't see how this is our issue. If TE isn't firing block change events then there's nothing I can do.

It would be our issue if you could break the block using any tool without us firing a change notification but that's not what you've indicated.

**Comment by Ionaru** [comment]
The materials are also instantly broken by hand. Is this intentional?

**Comment by AfterLifeLochie** [comment]
No, it's not. It sounds like the material hardness might be wrong, which might explain why the wrench is breaking it immediately.

**Comment by iTimmyLP** [comment]
Lochie, i can break the Decorblocks with one-hit without TE. My little environment is only with LC

**Comment by AfterLifeLochie** [comment]
Yeah, the hardness must be wrong.

**Comment by AfterLifeLochie** [comment]
Can you please check if this is still an issue in the new experimental builds?

**Comment by Cronosus** [comment]
checked in b15, yes i can still instantly break decoravive blocks

**Comment by AfterLifeLochie** [comment]
Okay. I will need to have another look at this again. Can you tell me which version of Thermal Expansion is installed when testing?

**Comment by Cronosus** [comment]
i use hand, without thermal...
with thermal wrench not remove block (rightclick), but leftclick (mine) instantly

**Comment by AfterLifeLochie** [comment]
Can you please test this in the next build?

**Comment by Cronosus** [comment]
yes... LanteaCraft-1.7.10-15

i can still destroy instantly:
-decor blocks (all)
-braziers (all)
-transporter ring (block)
-obelisks (all)
-doors (both)

**Comment by AfterLifeLochie** [comment]
So as par your edit, this doesn't happen any more?

**Comment by Cronosus** [comment]
Decor ok in last build (unst 16), except listed above.. i look into code, and all missing setHardness(); in code

quote: "So as par your edit, this doesn't happen any more?"
Sorry but i don't fully understand.. :(

**Comment by AfterLifeLochie** [comment]
Should be fixed (again) as of c8b78dba2e78f6b759385021b7a802c7c5c0853a.
