### ISSUE TITLE
Ability to move through Stargate components

### ISSUE THREAD

**Issue by Ionaru** [PC-Logix/LanteaCraft#305]
~~When holding the left mouse button (as in trying to break a block)~~ You are able to move through all stargate component blocks of all the stargates (ring, chevron and base). Also occurs without holding the left mouse button.

![2015-03-29_15 48 43](https://cloud.githubusercontent.com/assets/3472373/6885681/32119332-d62b-11e4-8479-78730ecbc6c1.png)

![2015-03-29_15 49 05](https://cloud.githubusercontent.com/assets/3472373/6885682/35b44426-d62b-11e4-92bb-26232eab9319.png)

I'm not sure if this is a bug or it's supposed to be this way, just seemed odd to me.

**Comment by AfterLifeLochie** [comment]
Can you isolate this in an environment with just LanteaCraft?

**Comment by hehe3301** [comment]
I can not replicate, with LC 1.7.10-68  and forge 10.13.3.1355

**Comment by Ionaru** [comment]
Neither can I.

**Comment by AfterLifeLochie** [comment]
This could be an interaction issue with any mod and LanteaCraft, though I do not see why a mod would be overriding our block's (or any other mods') hitboxes for clipping.

Can you please generate a list of all the mods in your environment (with their versions)?

**Comment by Ionaru** [comment]
http://pastebin.com/SpP2wc96

I'm no longer able to reproduce the issue after updating some of the mods in the modpack. Consider solved on my end.

Mods changed since issue report:
+RemainInMotion 2.5.3
~LanteaCraft 68 -> 70
~Applied Energistics rv2-beta-18 -> rv2-beta-28
~iChunUtil 4.2.1 -> 4.2.2
~Thermal Dynamics RC7-98 -> RC8-105
~Hardcore Ender Expansion 1.7.1 -> 1.8
~OpenComputers 1.5.4.11 -> 1.5.6.13
