### ISSUE TITLE
Please change the oreDict

### ISSUE THREAD

**Issue by iTimmyLP** [PC-Logix/LanteaCraft#306]
Can you change the oreDict, please? LC is not compatible with naquadah from other mods.
![oredict](https://cloud.githubusercontent.com/assets/6671741/6993383/a5ca5a40-daf2-11e4-802e-1b88f94371d5.png)

**Comment by AfterLifeLochie** [comment]
We did this because GregTech was breaking all of the recipes, and we had other people complaining about it.

**Comment by iTimmyLP** [comment]
OK, can you cut it to LC:oreNaquadah ore something like that? LanteaCraft:oreNaquadah ist to long for the Digital Miner from Mekanism

**Comment by AfterLifeLochie** [comment]
You should just be able to type `*:oreNaquadah` or just `*Naquadah` in an oredict filter.

Alternatively, just use `*` and mine everything.

**Comment by iTimmyLP** [comment]
*Naquadah works, thanks
