### ISSUE TITLE
double item drops

### ISSUE THREAD

**Issue by IndianaJohns** [PC-Logix/LanteaCraft#307]
I'm sorry. I do not speak English. I use the translator. On my server this bug. If the player kills the ejection opening of the gate, things fall in double. Server version cauldron 1.7.10 1307.

**Comment by iTimmyLP** [comment]
The Horizone kills people, that is a feature from LC. In the series the horizone kills and destroys everything

**Comment by IndianaJohns** [comment]
but things remain dead, they do not disappear. And comes in a double size. Copies of things

**Comment by AfterLifeLochie** [comment]
Do you mean that you get two copies of all the dropped player items?

**Comment by IndianaJohns** [comment]
yes! ;-)

**Comment by AfterLifeLochie** [comment]
Can you give me a list of all the mods you have installed currently?

If you are playing on a Cauldron server, can you test this without Cauldron installed to see if you still get two copies of the dropped items?

**Comment by IndianaJohns** [comment]
I found the cause of duplication of things. Things are duplicated in the region where the WorldGuard flag item-drop deny. Without him, no duplicates. WG version - 6

**Comment by Radviger** [comment]
Known bug with WorldGuard. I too have this issue :crap:

**Comment by AfterLifeLochie** [comment]
In which case, there's nothing I can do to fix it -- there's no external way for me to sensibly work around a plugin.
