### ISSUE TITLE
Computer craft code

### ISSUE THREAD

**Issue by ConradCreeper** [PC-Logix/LanteaCraft#309]
I know that Computer craft is supported and I've watched a video on how to use computer craft with the mod but it does not work. can you give me a list of directions and the code needed to program the computer to dial the gate. I want to be able t fast dial.

**Comment by Kodos-Atoz** [comment]
This isn't an issue, you should really use MCF for this

**Comment by AfterLifeLochie** [comment]
There are plenty of DHD programs out there (like [this one](http://www.computercraft.info/forums2/index.php?/topic/16656-lanteacraft-sgcraft-ccdhd-20-rc8f/)) which you could have used to see how to do it.

This issue tracker is not a discussion board. You should be posting this content to the [MCF thread](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292427-lanteacraft?page=92) instead. Do not do this again, please.
