### ISSUE TITLE
Stargate ring too narrow

### ISSUE THREAD

**Issue by Ionaru** [PC-Logix/LanteaCraft#311]
LanteaCraft is amazing and it does a great stuff of adding Stargate related stuff into the game. However the stargate itself seems a bit too narrow for me. 

![image](https://cloud.githubusercontent.com/assets/3472373/7079628/cddfac64-df26-11e4-8c12-7c056ed377a1.png)
As you can see in this picture, the ring is wider than the engineer working on it on the left. I'd say the stargate ring is about 0.80-0.90 meters wide, give or take.

![2015-04-10_02 10 18](https://cloud.githubusercontent.com/assets/3472373/7079668/6134d35e-df27-11e4-855a-db519384127b.png)
Now the SG-1 stargate in LanteaCraft seems to be a bit smaller than that. About half or even less the shoulder-width of my character, which is approximately 1 meter.

Is there a specific reason for the gate to be like this? Or can it be changed?

**Comment by AfterLifeLochie** [comment]
This is literally just an issue with the model.

**Comment by Ionaru** [comment]
Okay cool, so that will be in the 2.0 rewrite. Any idea in what sort of timeframe that will be available?

**Comment by Jeremythewiz** [comment]
Hey Ionaru. What mod do you use for the thingy that is attached to your stargate. I can't think of a better word except "thingy" lol. Here is what I'm talking about
![6134d35e-df27-11e4-855a-db519384127b](https://cloud.githubusercontent.com/assets/11890641/7094681/8117fc90-df91-11e4-906d-1598017b0ac9.png)

**Comment by iTimmyLP** [comment]
i think that this things are microblocks or something like this

**Comment by Jeremythewiz** [comment]
What're microblocks?

**Comment by iTimmyLP** [comment]
with the mod forgemicroblocks you can use a saw to cut blocks in pieces

**Comment by Ionaru** [comment]
Yep, I used Forge Microblocks for that.

**Comment by iTimmyLP** [comment]
i like this idea :D 
@AfterLifeLochie is it possible to add a thingy model that looks like the thingy "claws" in the series that is holding and powering the Gate?

**Comment by Jeremythewiz** [comment]
I agree with iTimmyLP

**Comment by Zunth5** [comment]
I believe those thingy "claws" are the superconductor attachments that power the earth gate. While I believe they appear to be supercooled in the series (thus the smoke) maybe they could be implimented as an alternative power conduit instead of using a DHD. It would probably be cool if this could be used as an alternate cc connection point, although im not in bed with the idea.

**Comment by AfterLifeLochie** [comment]
The new scaled model now actually has (somewhat) fixed chevrons and addresses the width issue described here:

![2015-04-14_15 42 29](https://cloud.githubusercontent.com/assets/123710/7131009/f15c58ec-e2bc-11e4-85a8-c5e14ce3a4d0.png)

**Comment by Ionaru** [comment]
That looks amazing! I don't know of it's the perspective but it looks kinda small.

**Comment by AfterLifeLochie** [comment]
The perspective doesn't show it, but the Stargate is now double the width it was previously. It's now approximately the width of a player.

**Comment by Zunth5** [comment]
I beleive lonaru is referring to the actual diameter of the gate. By my calculation based on the hight of an average human male; a "true" conversion of gate diameter in blocks would be roughly 7.4. 

By this estimate and the fact that a minecraft character is wider than a normal human, the size of the gates may be seen as a little small. It would be interesting to see a 9x9 gate model that would be closer to the proportional width of a minecraft character. I do not believe this would provide any other benifit aside from making gates harder to make and aesthetics.

**Comment by Ionaru** [comment]
Yes, I meant the diameter.

**Comment by AfterLifeLochie** [comment]
> a 9x9 gate model
> aside from making gates harder to make

I already have enough complaints about the difficulty of the mod (like finding Tok'ra villagers, for example). I don't see how making things more complicated is even remotely in my interests, really. 

I've resized the model to make it to *scale*, meaning that it fits within the established Stargate pattern we've used for so long. The model now looks like it appropriately fits in scale with other elements of the game in a way which doesn't make it look like some overly-ridiculous monolith.

**Comment by Jeremythewiz** [comment]
So here's my two cents. As long as it's cannon, it's good. If not then I think the mod is failing (no offense Lochie, this is still definitely the best SG mod). 
Also, are you planning on adding those things on the sides of the gate in the SGC?

**Comment by AfterLifeLochie** [comment]
> As long as it's cannon, it's good. If not then I think the mod is failing.

You're talking about canon in a context where, in Minecraft, it's possible to carry 2304 cubic meters of solid rock in seemingly *nothing* and without any kind of impediment, notwithstanding the fact that'd weigh more than one man could conceivably ever carry?

Maybe it's just me, but in that context, the expectation that things will be absolutely canon is stupid bordering on the absurd.

**Comment by Jeremythewiz** [comment]
I meant having the mod be cannon to the show. Or as close to it as possible, I understand that for obvious reasons it can't be 100% but close to it is nice

**Comment by Zunth5** [comment]
>I already have enough complaints about the difficulty of the mod (like finding Tok'ra villagers, for example). I don't see how making things more complicated is even remotely in my interests, really. 

I did mean that it could be seen as a benefit, not that was necessarily in current interest. Kinda sucks people are complaining when the difficulty when the mod itself provides some pretty awesome benefits. 

>I've resized the model to make it to scale, meaning that it fits within the established Stargate pattern we've used for so long. The model now looks like it appropriately fits in scale with other elements of the game in a way which doesn't make it look like some overly-ridiculous monolith.

I do like the current block pattern's simplicity and the gate in the above response looks amazing, especially with the larger constellations. I do like the current size (despite my comment before). I was probably giving a suggestion you probably have heard more than once.

I will not comment on this specific issue any further as the horse is good and dead.
