### ISSUE TITLE
Seeking info on 2.0

### ISSUE THREAD

**Issue by Jeremythewiz** [PC-Logix/LanteaCraft#312]
Hey guys. I've been using this mod for awhile now but I just discovered that it had an official forum. I've always wondered if weapons, wraith, the iris, etc were going to be added and it's good to know that there's actually progress working towards this.
So I have a few questions and please excuse me if they've already been asked or they seem naive, like I said, I'm new here.
1: Do you have a rough time frame for when 2.0 will be released?
2: I have encountered a bug where when you step through the stargate, it will be turned off on the receiving end after you step through. Not a huge issue, just a cannon problem.
3: Another bug I've found is the Naquadah generators will randomly turn off and you will have to destroy them and then replace them to get it turned back on.
4: Do you intend on adding the Pegasus DHD?
5: It would be closer to the cannon if you changed the DHD's name from "Stargate Controller" to something like "DHD" or "Dial Home Device"
6: Will you have the iris different for the Pegasus and Milky Way gates? To stay at least semi true to the cannon.
7: I don't think your texture for the DHD control crystal is correct either, I believe they're supposed to look like this (at least for the Pegasus DHD's. If you plan on adding them.)
![images](https://cloud.githubusercontent.com/assets/11890641/7093516/e3c48566-df87-11e4-9e95-6f4f2c52db5a.jpg)
8: There are some lighting issues with the stairs included in this mod as well.
9: I think Lantean control consoles (from the atlantis control room) would be a nice addition
10: I don't know if it would be possible, but the addition of Puddle Jumpers would be awesome.
Alright that's all my questions. Sorry for so many but I like to be thorugh. 
And while I'm here, I should mention that this is definitely the best stargate mod I've found. Keep up the good work :)

**Comment by Kodos-Atoz** [comment]
This is an issue tracker, for bug reports.  I'd suggest moving this to the forums.

**Comment by Jeremythewiz** [comment]
Whoops. My bad

**Comment by Jeremythewiz** [comment]
Um.... this may sound dumb but how do I move this? I can't even seem to delete this :/

**Comment by Kodos-Atoz** [comment]
Edit your most recent comment, and instead of hitting 'comment', hit close and comment

**Comment by AfterLifeLochie** [comment]
This is not how you should be using an issue tracker. Issues on an issue tracker are for bugs or suggestions only, and one bug/suggestion per issue.

If you do not know if you should post an issue here, consult [this handy tool](http://afterlifelochie.net/can-i-issue/) to see what you should do.
