### ISSUE TITLE
Questions About 2.0 Progress and Current Bugs

### ISSUE THREAD

**Issue by Jeremythewiz** [PC-Logix/LanteaCraft#313]
Hey guys. I've been using this mod for awhile now but I just discovered that it had an official forum. I've always wondered if weapons, wraith, the iris, etc were going to be added and it's good to know that there's actually progress working towards this.
So I have a few questions and please excuse me if they've already been asked or they seem naive, like I said, I'm new here.
1: Do you have a rough time frame for when 2.0 will be released?
2: I have encountered a bug where when you step through the stargate, it will be turned off on the receiving end after you step through. Not a huge issue, just a cannon problem.
3: Another bug I've found is the Naquadah generators will randomly turn off and you will have to destroy them and then replace them to get it turned back on.
4: Do you intend on adding the Pegasus DHD?
5: It would be closer to the cannon if you changed the DHD's name from "Stargate Controller" to something like "DHD" or "Dial Home Device"
6: Will you have the iris different for the Pegasus and Milky Way gates? To stay at least semi true to the cannon.
7: I don't think your texture for the DHD control crystal is correct either, I believe they're supposed to look like this (at least for the Pegasus DHD's. If you plan on adding them.)
![e3c48566-df87-11e4-9e95-6f4f2c52db5a](https://cloud.githubusercontent.com/assets/11890641/7093763/0ae117d4-df8a-11e4-874f-a208c7a8d8cc.jpg)
8: There are some lighting issues with the stairs included in this mod as well.
9: I think Lantean control consoles (from the atlantis control room) would be a nice addition
10: I don't know if it would be possible, but the addition of Puddle Jumpers would be awesome.
11: Are there currently any plans for the use of Naquadriah and Liquid Naquadah?
12: And the transporters from Atlantis would be pretty nice.
13: Are you planning on creating a MALP?
Alright that's all my questions. Sorry for so many but I like to be thorugh.
And while I'm here, I should mention that this is definitely the best stargate mod I've found. Keep up the good work :)

**Comment by Jeremythewiz** [comment]
I know some of these questions may not belong in here but I also have some bugs in this post so I figured I might as well group them together

**Comment by Sarous** [comment]
Some of these questions are answered on the wiki: http://lanteacraft.com/wiki/Main_Page

**Comment by iTimmyLP** [comment]
@Jeremythewiz A Tipp: Just follow @AfterLifeLochie on Twitter. There you can see always the progress from LC
#4 of you list:
![ss 2015-04-11 at 09 19 30](https://cloud.githubusercontent.com/assets/6671741/7100605/2e9a7650-e02c-11e4-9f88-e4c8197624d9.jpg)
![ss 2015-04-11 at 09 18 44](https://cloud.githubusercontent.com/assets/6671741/7100606/33c1bb98-e02c-11e4-9536-fe57cc7a759b.jpg)

**Comment by JohnOptegrove** [comment]
I don't think the iris is naturally "different" for Pegasus and Milky Way gates, it's just a different method of iris that can be applied to both gates (in-universe). A single slot in both styles of gate that would accept both irises would probably be the best solution.

**Comment by Jeremythewiz** [comment]
Hey thanks for the help guys. I'm not a huge fan of twitter but I'll probably check out his page. I agree with JohnOptegrove about the iris, thats a really good idea.

**Comment by AfterLifeLochie** [comment]
To all concerned; this is not how you should be using an issue tracker. Issues on an issue tracker are for bugs or suggestions only, and one bug/suggestion per issue. 

Please keep the content of issue tracker discussions on topic; I have great difficulty isolating the true issue and real points if an issue becomes a discussion about something not relevant to the original description of the issue or bug.

I reserve the right to remove comments or content which aren't on topic; this is the only warning you'll get henceforth. It has become impossible for me to manage this tracker with the way it's being used (repeatedly) by some individuals.

While I understand you might be new, there is some basic issue-tracker etiquette you're expected to follow. If you do not know if you should post an issue here, consult [this handy tool](http://afterlifelochie.net/can-i-issue/) to see what you should do.
