### ISSUE TITLE
Transport to other maps???

### ISSUE THREAD

**Issue by tvk1372** [PC-Logix/LanteaCraft#316]
Is it possible  to transport to my other maps by using  the stargate?
I tried it but,nothing..
I put a stargate in my desert map I copy the adress from the gate and put another gate in my flat map,but nothing.
Is there any way to transport with the stargate to other maps that I made?
Please help me!

**Comment by mRichard629** [comment]
another map is more or less another server instance, i don't think you can stargate to other servers

**Comment by hehe3301** [comment]
This mod allows teleportation between dimensions and within the same
dimension it does not allow teleportation between different worlds or saves.

**Comment by CaitlynMainer** [comment]
What they said,You can move between dimensions within the same save, but you can not move between saves.
