### ISSUE TITLE
creative power supply

### ISSUE THREAD

**Issue by joshthegrate** [PC-Logix/LanteaCraft#317]
im setting up a server and there will be a portal in the spawn for public use.

**Comment by CaitlynMainer** [comment]
I'm not sure what this is for...  Are you requesting this? Are you asking if it's possible?  We're not going to add creative power generation is that what this is about...

**Comment by joshthegrate** [comment]
Ya this would be for server owners that want to have an always powered gate in there spawn.

**Comment by mRichard629** [comment]
I do believe that's possible with a simple config setting , but it would only be between 2 gates. And no one could dial either one until they disconnected

**Comment by mrcgamer** [comment]
I believe that each of the power mods that interacts with the gates have a
creative power for your infinite power.

**Comment by joshthegrate** [comment]
I'm not referring to keeping a gate active I'm referring to not having to change the energy supply on a spawn town portal.

**Comment by joshthegrate** [comment]
Mrcgamer I have tried to connect one to a thermal expansion creative cell directly and via its conduits but they don't work.

**Comment by mrcgamer** [comment]
I'm not sure then I haven't messed with the mod in awhile.

**Comment by AfterLifeLochie** [comment]
Upgrade to the latest version. Power isn't required. 

I will be adding an infinite energy item at some stage for this exact reason.
