### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by HardInk** [PC-Logix/LanteaCraft#323]
Is this mod in standstill right now? I am an adept modder for 1.7.10 and would be more than happy to contribute ideas and assistnce

**Comment by Kodos-Atoz** [comment]
This is an issue tracker.  Ask questions on the forums.

**Comment by AfterLifeLochie** [comment]
No, it's not in standstill - I just have commitments which either restrict my time to work periodically, or prevent me from doing effective work.
