### ISSUE TITLE
Iris/GDO absents

### ISSUE THREAD

**Issue by LivierG8** [PC-Logix/LanteaCraft#325]
Bonjour à tous

Je dois vraiment être idiot ou alors j'ai un problème ou je sais pas mais j'ai vu dans les sources GitHub du mod que l'Iris et le GDO ont été inclu dans le mod, j'ai téléchargé la dernière version et ils n'y étaient pas. J'ai même changé le fichier de_DE.lang en en_US.lang parce que je savais qu'ils étaient dans le de_DE.lang mais rien n'y fait, ils n'apparaissent toujours pas. Je suis avec la dernière verion de Forge pour Minecraft 1.7.10 et j'ai la version 1.7.10-70 du mod (la dernière listée ici http://cdn.afterlifelochie.net/mods/lanteacraft/ ). Pouvez-vous m'aider s'il-vous-plaît ?

Merci

Livier

**Comment by mRichard629** [comment]
l'iris et GDO ne sont pas activés dans Lanteacraft 1.7.10.70 je souhaite qu'ils étaient

**Comment by LivierG8** [comment]
Bon, merci quand même
 
Ce que j'ai du mal à comprendre c'est pourquoi des vidéos en allemand montrent des objets de Lanteacraft que l'on ne peut pas avoir nous ?

**Comment by CaitlynMainer** [comment]
Link to the video in question?

**Comment by mRichard629** [comment]
peut-être qu'ils ont construit leur propre fourchette

**Comment by LivierG8** [comment]
CaitlynMainer : The link is exactly https://youtu.be/1Yiq6Cy89_o?t=15 where we can see that the author of this video can have "GDO", "Tok'Ra egg", "Ring activator", and some other

mRichard629 : Je ne pense pas parce qu'on dirait une vieille version (je ne vois qu'un seul menu pour les décos, la porte et le réacteur à Naquadah alors que dans la dernière, ces trois catégories sont séparées en trois menus bien distincts)

**Comment by CaitlynMainer** [comment]
He never uses the Iris though.. does he? The items exist in code, they do not function.

**Comment by AfterLifeLochie** [comment]
Hello Livier,

Often, I will make videos from my development environment - which has these unstable items available for me to use and test with. You won't be able to see these in your version as our build-service disables them automatically.

I'm not sure which videos you're talking about, but we don't have any control over what people say or present in them. I can only suggest you look at our wiki as an official guide - as Caitlyn and I are the only people who can update it.

I would encourage you to speak English on this tracker as much as is possible; it means I can quickly read your issue and your responses, even if they make little sense. I can't translate your issue texts when I'm on a mobile device, so you will get a very delayed reply from me.

**Comment by LivierG8** [comment]
Van I help by testing ?
