### ISSUE TITLE
How can I use the transporter rings in 1.7.10?

### ISSUE THREAD

**Issue by ElKockito** [PC-Logix/LanteaCraft#326]

**Comment by CaitlynMainer** [comment]
You don't, they've been disabled for quiet a while.

**Comment by hehe3301** [comment]
Are they planned to be re-enabled ?

**Comment by ElKockito** [comment]
Thanks

**Comment by CaitlynMainer** [comment]
@hehe3301 in the rewrite eventually I'm sure.

**Comment by AfterLifeLochie** [comment]
@ElKockito, please do not use the issue tracker to ask questions.

If you are unsure if you should open an issue here, please consult with the "Should I open an issue?" tool at http://afterlifelochie.net/can-i-issue/
