### ISSUE TITLE
How to enable 16x textures

### ISSUE THREAD

**Issue by WolfieWaffle** [PC-Logix/LanteaCraft#327]
I see that 16x textures exist, but how do I use them?

**Comment by lyqyd** [comment]
This question should likely be asked elsewhere, please see http://afterlifelochie.net/can-i-issue/

**Comment by hehe3301** [comment]
Is there a way to like github comments, because that ^ made my evening

**Comment by AfterLifeLochie** [comment]
![11201126_1618430065096826_4155804977169859412_o](https://cloud.githubusercontent.com/assets/123710/8270251/15a144fa-181a-11e5-8cf3-37f9ba0acbdd.jpg)

Please stop abusing this tracker, or I will just straight up turn it off.
