### ISSUE TITLE
Lanteacraft 1.7.10

### ISSUE THREAD

**Issue by DezeSentinel** [PC-Logix/LanteaCraft#328]
Hello, when will that transport Rings do they walk? I need it for my server! If you like it !!!!

**Comment by CaitlynMainer** [comment]
Duplicate of #326 

As stated there, the issue tracker is not for questions, use the Thread on Minecraft Forums.

**Comment by DezeSentinel** [comment]
How her? I do not understand your question, sorry I speak basic french!

**Comment by CaitlynMainer** [comment]
Google Translate: Comme indiqué il, la question tracker est pas pour les questions, utilisez le post sur les forums Minecraft. http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292427-lanteacraft   Ils sont désactivés, vous ne pouvez pas les utiliser
