### ISSUE TITLE
LC2 1.7.10-5 Pressing orange button when address isn't 7 or 9 symbols crashes to desktop

### ISSUE THREAD

**Issue by HydrantHunter** [PC-Logix/LanteaCraft#329]
Tested with no address and incomplete addresses - both result in crash to desktop.

Forge: 10.13.2.1291
LC2 1.7.10-5
ComputerCraft 1.74pr30
Gopher's Peripherals 2.2pr1

Crash log: http://puu.sh/ixW2r.txt

**Comment by AfterLifeLochie** [comment]
Oops, my bad. Thanks for the report!

**Comment by AfterLifeLochie** [comment]
Resolved by 6ced43f, will be in the next build. Please let me know if you find any other bugs.

**Comment by AfterLifeLochie** [comment]
This is now fixed as of Build 8.
