### ISSUE TITLE
Enhancement: Clear DHD state

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#332]
this does not exist on a "real" dhd but it would be nice to just clear the dhd

**Comment by AfterLifeLochie** [comment]
I was considering this, but I'm not particularly sure how I'd like this behaviour to work in terms of interface or input.

**Comment by AfterLifeLochie** [comment]
I don't think clearing the DHD state is really useful, now that the DHD doesn't have a state.

**Comment by lieven121** [comment]
even trough it would be nice you can close it if you want no need to give you extra work
