### ISSUE TITLE
you can enter infinit amount of chevrons 2.0

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#333]
on 9 it stops visual but you can keep entering

**Comment by AfterLifeLochie** [comment]
Yes - this is because the DHD will let you press the buttons, but nothing will happen. It won't engage any chevrons, because no more are supported.

**Comment by lieven121** [comment]
But when I typed a lonh address Ihad to delete the access buttons and only then deleting the 9the chevron
For ex I type DHKVGTUKOFLD
it displays DHKVGTUKO
But you have to press backspace 3 times before you start deleting the O

P.s. Srr I should have said this in my first post
I will try to be more complete in the future
