### ISSUE TITLE
Enhancement: Show pending glyphs in DHD entry queue

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#334]
now in 2.0 you have to wait until the chevron is locked and to "delete them" its the same (you can enter before but it happens afther) a way to see the address when its typed/pasted would be nice for example: when you type a address you see it in light gray and if a chevron is locked its colored dark gray (on a pegassus gate light blue and blue) 
and maybe let the chevrons in the GUI light up that would be cool but might be a bit hard

**Comment by AfterLifeLochie** [comment]
I was already considering some way of displaying the pending glyph in the DHD, simply because it's a bit strange to not see the typed address.
