### ISSUE TITLE
LC2-8 NEI interferes with some typing-based interfaces

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#335]
if you press P for example it potions and the potions "tab" of NEI opens and it would be nice that Nei doest show up in the DHD (or in the far future a plugin off nei that reminds gate addresses so you can save like 4 addresses)

**Comment by AfterLifeLochie** [comment]
NEI is probably hooking the keyboard in a strange way. I'll have to figure out some way of disabling it for our GUI's.

**Comment by hunator** [comment]
I can confirm this bug. It is still present in LC2-10, it reacts on keys: 
- E (closes DHD interface)
- P (potions tab)
- X (entirely free enchantments)
However NEI itself is not reacting on its keys (O, R, U in default conf.).

Also in my case DHD reacts only with sound, GUI isn't responding on button presses and gate also isn't reacting.

**Comment by AfterLifeLochie** [comment]
The NEI API is something pretty horrific, so there's little I can do about this issue. It might be possible for me to prevent NEI from handling the key-events by not forwarding them at all.

**Comment by lieven121** [comment]
I think this is fixed now :D 
thx and can any one close it
