### ISSUE TITLE
When entering a long address (longer then 9 chevrons) the gate keeps spinning ...

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#336]
When entering a long address (longer then 9 chevrons) the gate keeps spinning unitl all the chevrons are done so if you enter a 18 number long address the gate turns 18 times 
even he only locks 9 you have to w8 until he is done to do any thing else

**Comment by AfterLifeLochie** [comment]
This is a known logic bug.

When pushing command states, the size of the queue and the glyph on/off status is ignored, so the "future" number of glyphs isn't considered properly.

**Comment by AfterLifeLochie** [comment]
Resolved in commit c8e215a.
