### ISSUE TITLE
LC2-8 Strange behaviour at receiver gate

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#337]
if you press middle button the gate wont shut but somehow when pressing random buttons and middle one it closes

**Comment by AfterLifeLochie** [comment]
That's interesting. This is likely another logic issue, I'll have a look into it.

**Comment by HydrantHunter** [comment]
Could this also be related to the timeout in closed issue #372 ?  The time it takes to press a few random buttons before pressing the orange button could be enough time for the timeout to pass...

**Comment by lieven121** [comment]
currently after quick testing i think this is no problem anymore

**Comment by AfterLifeLochie** [comment]
I'm sure I've fixed this, please let me know.

**Comment by lieven121** [comment]
You can close it if you want i wasnt able to reproduce with new version
