### ISSUE TITLE
LC2-8 Chevron rendering/state issue

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#338]
when entering addresses with paste the chevrons can sometimes ( actually very offen depends on the address) lock faster than the one before them

**Comment by AfterLifeLochie** [comment]
What do you mean when you say "lock faster"?

**Comment by lieven121** [comment]
for ex chevron 8 is locked and then chevron 7 
8 is bottem right 7 is top left
i wanted to make a vid but didt found a good screen recorder :(

**Comment by AfterLifeLochie** [comment]
Right. I'll do some more investigating to see if I can replicate this issue at my end.

**Comment by lieven121** [comment]
ok normaly the address 123456789 works always for me on different gates

**Comment by lieven121** [comment]
maybe just increase the time between chevrons that worked for me (with computercraft)
