### ISSUE TITLE
LC2-8 SoundSystem throws unchecked exceptions.

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#339]
i enterd 123456789 and (afther a while) pressed the dhd button
http://pastebin.com/xvxQPqhT

**Comment by AfterLifeLochie** [comment]
Have you been able to repeat this issue more than one time?

**Comment by lieven121** [comment]
no maybe it was just a rare ocasion thing

**Comment by AfterLifeLochie** [comment]
I have added additional recovery-case conditional logic in commit c774356 which will hopefully prevent issues like this from occurring in the future. LC should be able to recover from this situation if it happens again.

A fix will appear in the next build.
