### ISSUE TITLE
LC2-8 Lantean Door behaviour issues

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#341]
bug nr1
when placing 2 doors on top (total 4 blocks high)
if you break the seccond block from the ground up only the top block(block nr 4) stays 
if you break the third block from the ground up only the bottom block (block nr 1) stays 
bug nr2
its hard to explain everytime you give a rs pulse the door wil turn more so afther a few pulses the gate spins , depening on how much you switch the lever how more turns the door will do

to test this just place a door place a lever and pull it +- 10 times

**Comment by lieven121** [comment]
here is a pic 
![2016-03-21_16 32 12](https://cloud.githubusercontent.com/assets/7773244/13923875/8b0de8e8-ef82-11e5-8399-2b48b11b244e.png)
the right doors I placed by placing the bottom door second

**Comment by AfterLifeLochie** [comment]
Yeah, the textures and behaviours are a little messed up, because I allow the placement of a two-block high door initially and then a one-high extension on this. The code needs a massive fix.

**Comment by AfterLifeLochie** [comment]
This should be addressed in fd8fa4ffe72965169ab69b8b646cf4ad53ff610a, see issue #437.
