### ISSUE TITLE
Enhancement: Signals through Stargates.

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#342]
a way to send a cc command trough a gate 
--maybe wireless
--or wired msges trough the adaptor

**Comment by AfterLifeLochie** [comment]
This will be done in the future, but it requires some hacking on my part to make it work properly.

**Comment by AfterLifeLochie** [comment]
You should be able to send signals through the Stargate using the `sendMessage` function; the receiving Stargate will trigger an event with the data contained in the message sent.

**Comment by HydrantHunter** [comment]
sendMessage seems to work (no errors generated when it's called), but no corresponding event is generated on the receiving end that I can tell.

**Comment by lieven121** [comment]
does this also include that every wireless msg is also sent trough the gate (not directed to the gate but just like a repeater (like if you run the repeat program on a cc pc)

**Comment by AfterLifeLochie** [comment]
I'll have to check why this isn't working.

No - this does **not** include wireless signals; you must use the `sendMessage` function.

**Comment by lieven121** [comment]
Ow i havent checked it either currently wil do tommorow 
I was just wondering about if its possible

**Comment by lieven121** [comment]
yes I can confim now that its indeed not working
