### ISSUE TITLE
LC2-8 DHD address rendering crash

### ISSUE THREAD

**Issue by Timmy94W** [PC-Logix/LanteaCraft#343]
I can't realy explain how i have mad this.
I just have tried to open the DHD from the second Gate

uses version: Unstable 8

Crashlog: http://pastebin.com/Gw4ACCRv

**Comment by Timmy94W** [comment]
Sry for the multipost.

I have recreated the crash a few times more and one time i have recorded.
http://youtu.be/foN5n1qQk1c
I hope i could help you to find the mistake :D

**Comment by AfterLifeLochie** [comment]
I'm really having a hard time understanding what is going on here. There's just too much happening for me to understand what you're trying to demonstrate.

Can you please type out the exact steps for reproduction, and provide your `logs/lanteacraft/core.log` and `logs/lanteacraft/game.log` files, as well as your FML log?

**Comment by Timmy94W** [comment]
i have dial an address, went to the second gate, press random keys ( a - z | 1-0 ), hit enter, paste the address from the first gate with ctrl+v, hit again enter, wait a few seconds, than the event horizon disappears, the second gate start to dial. than i have right-clicked the dhd to open the interface, than crash

logfiles: http://t94.cwsurf.de/Neuer%20ZIP-komprimierter%20Ordner.zip

**Comment by AfterLifeLochie** [comment]
I have added a temporary workaround to see if I can isolate further the reason for this issue.

Can you please try and replicate this issue again in the next build which occurs, and let me know if the problem is present again? You will likely see a "`Problem rendering screen`" message in your console instead of a crash, so please check there instead.

**Comment by Timmy94W** [comment]
![2015-06-25_14 31 51](https://cloud.githubusercontent.com/assets/6671741/8354326/90687390-1b47-11e5-9e3f-302f1254b15b.png)

i don't see a "Problem rendering screen" message, but minecraft do not crash. 
the Gate stopped dial after 9 chevron.

The DHD is ignoring input until i hit a few times the Backspace key to clear the address

**Comment by AfterLifeLochie** [comment]
Can you check in the game console to make sure there's nothing being logged?

**Comment by Timmy94W** [comment]
I already have checked it. 
here ist my log folder: http://t94.cwsurf.de/Timmy94W-LC2-U8-Logs.zip

**Comment by AfterLifeLochie** [comment]
Hmm, okay. Please let me know if the issue returns, it might have been related to one of the other chevron-locking issues which I fixed earlier (or something). Thanks for the report!
