### ISSUE TITLE
for 2.0 somthing to detect a iris

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#344]
for when irises are added could there be something to send trough the gate and see if there is a iris
I could make a cc program that sends that out but not everyone uses computers + if they want you to die they wont say here is a iris 

just got a idea: maybe make a model of a MALP and make it a idel mob so it wont move but you can push it trough the gate and then look if MALP died (in chat there will come MALP was killed by iris or whatever the death msg is) or a remote for the MALP ,this would make it easyer on our side but not to code
I kown you can also name a pig MALP and do the same but I rather have a MALP in my gate room then a pig + you would need a lot of name tags

**Comment by AfterLifeLochie** [comment]
You won't be able to know if there's an iris present on the destination gate; that's part of the point of the iris in the first place.

There's already plans to add some of the things you've mentioned, but they're mostly duplicates of things already reported to me.

**Comment by lieven121** [comment]
Oké and srr for duping things its not my intention I try to look if it exists but sometimes I look over something or just didt read it well
