### ISSUE TITLE
DHD address adapts size

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#346]
since there is no support anymore for 7 chevrons addresses the addresses in the dhd adapting size is unnecessary

**Comment by AfterLifeLochie** [comment]
7-chevron addresses are supported, they're just not generated by default with Stargates which are placed in the world. 7-chevron addresses are reserved for special purposes.

**Comment by lieven121** [comment]
so should i support them in a cc program or not ?
(I know this isnt the place but I would find it weird to go one with this confersation on a other site or so)

**Comment by AfterLifeLochie** [comment]
Yes - you should consider both 7-chevron and 9-chevron addresses valid, though 7-chevron addresses will be very rare.

**Comment by lieven121** [comment]
could you in the future put one or two in the game to test my program
and how will a gate know when you want a 7 or a 9 because the when entering a 7 chevrons the last chervon is the bottem left and not the top one

**Comment by AfterLifeLochie** [comment]
It will probably look weird visually, yes. I didn't remove the code for 7-chevron support, in case someone edits the `addresses.json` and creates a 7-chevron address themselves.
