### ISSUE TITLE
LC2-14 part of the gate doesnt become visible again

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#350]
when you build a gate that is part on one chunk and a other part on a other chunk and break the base block the gate somtimes doesnt notify the other blocks (on the other chunk as the base block)
![2015-06-29_10 53 03](https://cloud.githubusercontent.com/assets/7773244/8404452/699bd4ec-1e4d-11e5-916c-ce09e78c0749.png)
a simple chunk update make them become visible again it works a lot (as far as i can see always) on high altitude and sometimes on the ground
edit: I tested with your glasses and they say Multibock:none on the invisible blocks
and a relog also makes them visible

**Comment by AfterLifeLochie** [comment]
Thanks for the report - it sounds like there might be an issue with marking the chunk for a render update on the client. :)

**Comment by AfterLifeLochie** [comment]
I'm not specifically sure how this is happening, can you give me coordinates of the parts of the gates if you have them handy? I'd ideally like to figure out if it's something to do with chunk order.

**Comment by AfterLifeLochie** [comment]
Can I get more info on the coordinates of the gates?

Without them, I can't diagnose this issue and will have to close the report.
