### ISSUE TITLE
gate's that are broken are stil functional LC2 build 10

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#351]
I realy taught I had seen this before but couldnt find it 
if I look over it just close it or merge and my exuses in advance  

a broken gate (not base block) can still dial/connect/disconnect/recieve
it all works but just isnt visible

**Comment by AfterLifeLochie** [comment]
This is because the current logic doesn't test to see if the structure is valid before allowing connections; it currently only affects rendering.

**Comment by AfterLifeLochie** [comment]
Fixed in commit 6c0aff6.
