### ISSUE TITLE
LC2-14 Gate Freezes On Invalid Address

### ISSUE THREAD

**Issue by Jeremythewiz** [PC-Logix/LanteaCraft#353]
I'm not sure if this is already known but if you type in an invalid address in the DHD and hit the orange activation button, the gate will freeze with all chevrons encoded and you have to break the base block to unfreeze it.
Also, sometimes, if you build a gate in an enclosed area, it won't form a gate. It will just remain as the ring and chevron blocks. But I noticed that when this happens, the lighting on the stargate blocks looks very dark and there's nothing I can do to get them back to normal.

**Comment by AfterLifeLochie** [comment]
The freezing you're seeing is likely the Stargate trying to connect. It has a very long timeout, in the event the server is very busy and can't load another world and/or chunks fast enough.

With regards to your second issue, can you isolate this problem with LanteaCraft alone? Enclosed spaces shouldn't cause an issue for Stargates so long as the centre ring space is unobstructed.

**Comment by AfterLifeLochie** [comment]
Unless I get some more information, I will have to close this.  If you could respond as soon as possible, that would be good - else I will assume this is no longer an issue.

**Comment by AfterLifeLochie** [comment]
Closing due to lack of response from @Jeremythewiz.
