### ISSUE TITLE
weird lighting blocks 

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#355]
almost all the blocks (exept 3d models) dont like a block south east 2 above them they turn black 
to show you this : 
![2015-07-07_19 15 36](https://cloud.githubusercontent.com/assets/7773244/8552573/3f727fc6-24de-11e5-9605-333ef67c8187.png)
![2015-07-07_19 15 49](https://cloud.githubusercontent.com/assets/7773244/8552575/3f73d574-24de-11e5-9d00-79d58acfa2ab.png)
![2015-07-07_19 18 04](https://cloud.githubusercontent.com/assets/7773244/8552574/3f72b9dc-24de-11e5-83eb-fddfbd71ed7d.png)
![2015-07-07_19 18 13](https://cloud.githubusercontent.com/assets/7773244/8552572/3f72639c-24de-11e5-8347-a346fd87df3d.png)
![2015-07-07_19 24 18](https://cloud.githubusercontent.com/assets/7773244/8552571/3f719c8c-24de-11e5-8577-52c005b356ec.png)

**Comment by AfterLifeLochie** [comment]
Fixed in commit e6ab74f. Thanks for the pick-up, I doubt I would have noticed this one otherwise.
