### ISSUE TITLE
gates only check if the chervon blocks are in place 

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#356]
like the title says a gate checks only if the chervon blocks are in place so you can make a gate completely out of chevron blocks or just here and there replace a ring block with a chevron one 
pictures 
![2015-07-07_19 34 44](https://cloud.githubusercontent.com/assets/7773244/8552724/42f6afd6-24df-11e5-8d08-0de9ab529489.png)
![2015-07-07_19 34 47](https://cloud.githubusercontent.com/assets/7773244/8552725/42fd9fe4-24df-11e5-9df1-e9cfab0a030f.png)
![2015-07-07_19 35 42](https://cloud.githubusercontent.com/assets/7773244/8552755/68f9c5ce-24df-11e5-9ce6-7235cba87907.png)
![2015-07-07_19 35 46](https://cloud.githubusercontent.com/assets/7773244/8552756/68fc4de4-24df-11e5-8a7b-d0e2ef7615a6.png)

**Comment by AfterLifeLochie** [comment]
Fixed in commit a78f26b.
