### ISSUE TITLE
Build 12 - Unhandled exception in ITickEventHandler

### ISSUE THREAD

**Issue by Kusinagie** [PC-Logix/LanteaCraft#357]
Happened to look at my log file and found this.

https://gist.github.com/Kusinagie/f01d3b615f3dadf3565a#file-sample-of-log

This spawned endlessly till i shut the client down. Full log file ended up being 63714kb. 

Java7u80
Using in modpack: direwolf20 1.5.0
Launcher: Feed the Beast: 1.4.7
......Been a while since i have done an error report. Let me know if you need more information.

**Comment by AfterLifeLochie** [comment]
Can you tarball up your `logs/lanteacraft` directory and send it this way?

**Comment by AfterLifeLochie** [comment]
Scratch that, I've found the source of the problem. Thank you for the report. :)
