### ISSUE TITLE
1.7.10-13 - CC computers won't boot if attached to a StargateBase

### ISSUE THREAD

**Issue by HydrantHunter** [PC-Logix/LanteaCraft#358]
With LC 1.7.10-13, CC computers attached to a StargateBase appear to either not boot at all or possibly shutdown due to yield protection.  CTL-R has no effect.  If placed elsewhere, the same computer will boot without issue.  The computer has no startup file.

Forge: 10.13.2.1291
LC: 1.7.10-13
CC: 1.74
Gopher's Peripherals: 2.2pr1

**Comment by AfterLifeLochie** [comment]
Dammit.

**Comment by lieven121** [comment]
Events also dont work and since I think its related to this I dont know if i should open a new issue

**Comment by HydrantHunter** [comment]
fwiw, setting down a computer, booting it, *then* throwing down the StargateBase to complete the gate allows the computer to work.  Having done that, lieven121 is correct - the gates are still not generating events.  I'll file a new issue.

**Comment by lieven121** [comment]
Aparently this is also a OC bug (see MC forum)

**Comment by AfterLifeLochie** [comment]
This is a bug caused by the integration driver system skipping nested constructors. I'll need to do some tweaking to make it work right.

**Comment by AfterLifeLochie** [comment]
I have tweaked the ComputerCraft and OC support systems to fix the issue using a workaround.

![ss 2015-07-10 at 11 17 31](https://cloud.githubusercontent.com/assets/123710/8610426/513d0370-26f5-11e5-9295-c9eed770605d.png)
