### ISSUE TITLE
LC2-14 The transportring teleportation is a 1 or 2 block(s) wrong

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#360]
for example you start in the middle and you end up not in the middle
, you stand on the edge and end up next to the platform
edit if you end up on a differen place (except next to the platform) and you tp again you will go back to your old location

**Comment by UnixRonin** [comment]
I have also observed this "off by one to two blocks" behavior with transport rings.  It is still present in build 19.  On one occasion I actually arrived standing *in the rings* — i.e. with rings passing through my body.  I've never had it return me to my original starting location on an immediate return trip; I'm guessing that was random chance.

(Yeah, it stung like hell.)

**Comment by AfterLifeLochie** [comment]
This is related to issue #381.
