### ISSUE TITLE
Only base block still makes sound and dust particles

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#363]
if you run a cc program the gate can still make sound and dust paricles

**Comment by AfterLifeLochie** [comment]
I don't understand what you're trying to describe here.

**Comment by lieven121** [comment]
realy srr mis clickked instead of comment close and this block can make sound and dust particles 
![2015-07-10_03 23 39](https://cloud.githubusercontent.com/assets/7773244/8610521/4166a592-26b3-11e5-83c4-f09c247d1fa9.png)

and having alo bug #359

**Comment by AfterLifeLochie** [comment]
I still don't understand; do you mean you can operate the block as if it were a working Stargate, or?

**Comment by lieven121** [comment]
yes but you cant teleport

**Comment by AfterLifeLochie** [comment]
Okay. I'll have a look into this.

**Comment by AfterLifeLochie** [comment]
Fixed in commit 4d2bf05.
