### ISSUE TITLE
LC-14 Crash when placing/interacting with DHD

### ISSUE THREAD

**Issue by UniversalMigrator** [PC-Logix/LanteaCraft#365]
Whenever placing or attempting to break or use a placed DHD in the world, MC disconnects from SMP server with Internal Server Error. Client logs don't show anything, however server side will show the following text with the second part of which spamming constantly until server is shutdown: http://pastebin.com/Q01vF7gS

Using Forge 1472 and the following mods (list too large to place here): http://pastebin.com/Xtnpvzre

**Comment by UniversalMigrator** [comment]
After more testing, this also occurs with any stargate blocks (base, ring, chevron) as well as decorative blocks such as braziers. Does not impact transport rings.

**Comment by AfterLifeLochie** [comment]
Can you please provide all the logging files in `logs/lanteacraft`?

**Comment by UniversalMigrator** [comment]
http://pastebin.com/2zyPh7YA game.log
http://pastebin.com/s9nDmUz7 performance.log
http://pastebin.com/BJnDHvnK core.log

Additional note; I noticed that my server machine was running some god old version of Java 7. it's been updated to the latest Java 8 release, both 32 and 64 bit.

**Comment by AfterLifeLochie** [comment]
This is unusual. Can I get a copy of the FML logs as well?

**Comment by UniversalMigrator** [comment]
FML log here: https://www.dropbox.com/s/adtcxgmi94g6k2z/fml-server-3.log?dl=0

**Comment by UniversalMigrator** [comment]
Another FML log: http://pastebin.com/9ARq9WxY

**Comment by AfterLifeLochie** [comment]
Okay, I see the issue now.

**Comment by AfterLifeLochie** [comment]
Todo: patch out `SoundCategory` because it's sideonly; wrap `LCBlock.func_149915_a` so that we trap `Class.newInstance` returning a `Throwable` (ie, feed to log, then throw upwards).

**Comment by AfterLifeLochie** [comment]
Fixed in commit c43e23f. Thanks for the report!
