### ISSUE TITLE
LC-14 Gate only forms in south direction

### ISSUE THREAD

**Issue by Timmy94W** [PC-Logix/LanteaCraft#366]
![2015-07-10_18 37 33](https://cloud.githubusercontent.com/assets/6671741/8623653/099796e6-2733-11e5-9608-b95b1e7eda5b.png)
![2015-07-10_18 37 48](https://cloud.githubusercontent.com/assets/6671741/8623654/099abbbe-2733-11e5-82e6-00a248ff1de9.png)
![2015-07-10_18 31 47](https://cloud.githubusercontent.com/assets/6671741/8623655/099d8b6e-2733-11e5-9c02-0380829f2bd2.png)

**Comment by AfterLifeLochie** [comment]
I am not able to replicate this issue in the latest version.

What other mods do you have installed? Can you please provide the contents of the `logs/lanteacraft` directory?

**Comment by Timmy94W** [comment]
CodeChickenLib-1.7.10-1.1.3.138-universal
CodeChickenCore-1.7.10-1.0.7.46-universal
ComputerCraft1.73
LanteaCraft-1.7.10-14 
neiaddons-1.12.10.33-mc1.7.10
NotEnoughItems-1.7.10-1.0.5.111-universal
OpenComputers-MC1.7.10-1.5.13.27-pre.1-universal
Waila-1.5.10_1.7.10

and the Logs you want: http://t94.cwsurf.de/lanteacraft.zip

**Comment by AfterLifeLochie** [comment]
Does this still happen in LC2-15?

**Comment by Timmy94W** [comment]
Yes it still does happen in LC2-15

**Comment by AfterLifeLochie** [comment]
I have been able to confirm this in development environment - it only occurs when the coordinates fall in the sign range (-x, +z), so I suspect a rounding error of some kind.

**Comment by AfterLifeLochie** [comment]
Should be addressed in 0be420f - when it comes out, let me know if you have any more issues. :)
