### ISSUE TITLE
Issue with -14 build from July

### ISSUE THREAD

**Issue by Cleardragonf** [PC-Logix/LanteaCraft#367]
Just a heads up but when i'm in creative mode in regulard minecraft the only items i can see are the transporter rings a few items and that's it...

**Comment by AfterLifeLochie** [comment]
Does this occur in the latest build?

Can you isolate this with just LanteaCraft installed?

**Comment by AfterLifeLochie** [comment]
Assuming this is no longer an issue.

**Comment by Cleardragonf** [comment]
Correct Sorry it took so long
