### ISSUE TITLE
build 14: [Server thread/WARN] [LanteaCraft/]: Problem populating features for chunk

### ISSUE THREAD

**Issue by Kusinagie** [PC-Logix/LanteaCraft#369]
Getting alot of these in the server log:

[Server thread/WARN] [LanteaCraft/]: Problem populating features for chunk
[Server thread/WARN] [LanteaCraft/]: Failed to generate structures

Fml-server-latest log as well as the 3 log files from the lanteacraft folder:
https://gist.github.com/Kusinagie/93f002f97bf6399328ab

Java7u80
Direwolf20 modpack v1.5.0
Feed the Beast launcher v1.4.7

**Comment by AfterLifeLochie** [comment]
Fixed in commit 5489366. Thanks for the report!
