### ISSUE TITLE
LC2-15 java.lang.ArrayIndexOutOfBoundsException: 15 when going from Nether to an unvisited part of the Overworld.

### ISSUE THREAD

**Issue by UniversalMigrator** [PC-Logix/LanteaCraft#370]
Was traveling via Nether, made a portal to the Overworld, upon the transfer to the Overworld, client crashes with java.lang.ArrayIndexOutOfBoundsException: 15. Removing LC allows transfer and loading of client to work as per normal, albeit with a large sandstone structure next to the nether portal with a slot for a stargate to stand on.

Client crash log: http://pastebin.com/0nCw8MJC
Client FML log: https://www.dropbox.com/s/ko2i477ivey75fj/fml-client-latest.log?dl=0
Client LC core.log: http://pastebin.com/3WjiK8fU
Client LC game.log: http://pastebin.com/r20v5bwC
Client LC performance.log:http://pastebin.com/z9sFmest

Server FML log: https://www.dropbox.com/s/lkfw75m7rplrnvm/fml-server-latest.log?dl=0
Server LC core.log: http://pastebin.com/1XApWjRY
Server LC game.log: http://pastebin.com/E673FpeV
Server LC performance.log: http://pastebin.com/T5G3jXtm

**Comment by AfterLifeLochie** [comment]
Can you provide me with a screenshot of the structure, the map seed and the coordinates?

**Comment by UniversalMigrator** [comment]
Screenshot: http://i.imgur.com/hJNXb69.jpg
Map seed: 8818756097821605706 on largebiomes
Coords (centre of structure): X -10488, Z -5115, Y 73
Portal from Nether was placed (in Nether) at: X -1311, Z -640. Y 33
Modlist is as per: http://pastebin.com/Xtnpvzre

**Comment by UniversalMigrator** [comment]
There's no gate shown there as I had to remove LC to be able to actually login to the server.

**Comment by AfterLifeLochie** [comment]
This should be fixed, but you will need to re-generate the whole world (or remove LanteaCraft & load all chunks) to remove erroneously placed Stargates. Thanks for the report!
