### ISSUE TITLE
LC2-15 Notable delay in all commands immediately after gate has connected

### ISSUE THREAD

**Issue by HydrantHunter** [PC-Logix/LanteaCraft#372]
Immediately after connecting to an address the dialing stargate appears to become unresponsive to commands.  In actuality the commands do eventually execute but after a rather long delay.  The longer you wait after a connection, the shorter the delay.  But once the delay has passed everything is immediately responsive.  It acts as if there is a timer that waits a certain amount of time after connection before executing new commands.

This occurs with the DHD and CC computers (eg. hit disconnect immediately after connecting and it takes awhile).  I realize this probably could use some clarification, so please let me know if I can provide more information.

Forge and other versions haven't changed from previous reports so I'll forgo those at this time.

EDIT: The delay from connection to first execution seems to be around 7 seconds.

**Comment by AfterLifeLochie** [comment]
This is probably related to issue #353.

**Comment by AfterLifeLochie** [comment]
The delay in response from the Stargate is probably related to the fact the Stargate will wait for 10 seconds in the ```CONNECT``` phase, and won't skip this timeout if a connection is a success.

Technically speaking, I could skip this delay - but originally I did it to prevent something like this:
```
while (true) do
   stargate.connect()
   stargate.disconnect()
end
```

As ```disconnect()``` does not clear the glyphs , it would be possible to force the server to load/unload a lot of chunks in quite a short period of time which would put it under a lot of strain.

Unless there's some real reason you'd want to immediately hang up a Stargate - though I don't much see the use of this - there's no reason for the code to skip any wait timeout.

**Comment by HydrantHunter** [comment]
Makes sense to me.  Now that I know it's there, I have no reason or need to skip the connect timer.  Thanks for taking the time to explain the process to me.  Consider this closed.
