### ISSUE TITLE
LC2-15 Gates generating 'connect' event even with non-existent addresses

### ISSUE THREAD

**Issue by HydrantHunter** [PC-Logix/LanteaCraft#374]
When dialing an invalid address (one that doesn't exist) and then engaging the stargate, the gate generates a 'connect' event even though a wormhole isn't established.

As always, please let me know if I can provide more info.

Forge: 10.13.2.1291
CC: 1.74
Gopher's Peripherals: 2.2pr1

**Comment by AfterLifeLochie** [comment]
This is because the Stargate returns the `connect` event when the connect command is performed; it doesn't indicate whether a connection has been established or not.

**Comment by AfterLifeLochie** [comment]
This should be changed for the next build. Note, you'll still get a `disconnect` event if the Stargate connection fails.
