### ISSUE TITLE
Obelisk String thing

### ISSUE THREAD

**Issue by Timmy94W** [PC-Logix/LanteaCraft#376]
![ss 2015-07-14 at 12 15 38 1](https://cloud.githubusercontent.com/assets/6671741/8671073/5e4eb088-2a22-11e5-905b-f03c42303466.png)

Is that right?

//edit:
Pick wrong picture. now it is the right one.

**Comment by AfterLifeLochie** [comment]
Yeah, it's just a problem with me not doing something in the source for the block.

The localization names are right, so *don't* change them.

**Comment by AfterLifeLochie** [comment]
Fixed in commit ddf114f.
