### ISSUE TITLE
A computer generates a peripheral_detach event on block update LC2 15

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#377]
like the title says the gate generates a peripheral_detach event everytime the computer gets a block update 

mods: 
-open Peripherals AIO (+ core mod)
-computercraft
-extra utilitys 
-lanteacraft
-not enaugh items (+core mod)

**Comment by AfterLifeLochie** [comment]
I don't send the `peripheral_detach` event from code.

**Comment by lieven121** [comment]
I dont know what is causing it to but if you want to test it you can use 
"lua"
"os.pullEvent("peripheral_detach")"
and just place a block next to the computer

**Comment by AfterLifeLochie** [comment]
I can see this behaviour now, but I'll be damned if I know what it is being caused by.

Guess it's time to bust out the disassembler and a chainsaw.

**Comment by lyqyd** [comment]
Unless you override this function to make it do something useful after this declaration, [this](https://github.com/PC-Logix/LanteaCraft/blob/master/src/main/java/lc/common/impl/drivers/ComputerCraftPeripheralDriver.java#L108) is likely your culprit.  I've used [this](https://github.com/Cloudhunter/OpenCCSensors/blob/master/src/main/java/openccsensors/common/peripheral/PeripheralSensor.java#L302) with some success, though you may want something entirely different.  Either way, the equals method appears to be used by ComputerCraft to invalidate the existing IPeripheral if a new one requested for that location isn't "equal" to the existing one, or something like that.

**Comment by AfterLifeLochie** [comment]
It would be great if a developer (or someone) over there could responsibly document [the method in question](https://github.com/PC-Logix/LanteaCraft/blob/master/src/externs/java/dan200/computercraft/api/peripheral/IPeripheral.java#L96-L99).
