### ISSUE TITLE
Iris?

### ISSUE THREAD

**Issue by joneschrisan** [PC-Logix/LanteaCraft#378]
I've noticed Iris in the code but nothing on the wiki. Is this working yet?

**Comment by AfterLifeLochie** [comment]
If it appears in code and not on the wiki (or the wiki has no information about it), then it's likely a feature I am working on and is therefore not useable.

Please do not use the issue tracker to ask ques tions; we prefer you check (and utilize) the forums instead. If you are unsure if you should open an issue or post at the forum, please consult http://afterlifelochie.net/can-i-issue .

**Comment by joneschrisan** [comment]
Fair point but github has a method to turn isues into suggested features. Hence why I asked here.

**Comment by AfterLifeLochie** [comment]
I am aware - but a cursory search could have answered your questions about irises. They've been asked about many times (both on the thread, and here) and I'm sure I've posted on the thread at least once about it. 

While I appreciate all suggestions and comments, it is seriously frustrating getting the same questions asked many times - which could be answered with a simple search.

**Comment by joneschrisan** [comment]
Again fair point, no-one likes being asked the same questions over and over again. But there's nothing on a saearch in the wiki, site, or forums about an iris, and on here seaching the issues, only talking about what an iris does. Nothing about if it's been implemented yet.
