### ISSUE TITLE
Two gates with the same address

### ISSUE THREAD

**Issue by joneschrisan** [PC-Logix/LanteaCraft#379]
I placed 3 gates in this format

![stargates](https://cloud.githubusercontent.com/assets/1489398/9295333/60411b74-4462-11e5-8f92-caa685841134.png)

All far enough away from each other.

A - Milkyway gate - Top in pic.
B - Pegasus gate - Right in pic.
C - Wraith gate - Left in pic.

A, then B, then C.

When I placed C, it was given the same address as A.
When I dial A or C from B it dials C but all 3 open.
I can not dial from A or C.

**Comment by AfterLifeLochie** [comment]
Can you please provide your `saves/<save-name>/lanteacraft/addresses.json` file, and the coordinates of all stargate base blocks?

**Comment by joneschrisan** [comment]
No such directory.

**Comment by AfterLifeLochie** [comment]
Which version of LC are you current using?

**Comment by joneschrisan** [comment]
1.7.10-70

**Comment by AfterLifeLochie** [comment]
It appears as if the Stargates are in the same chunk, which will cause this issue.

You should consider upgrading to LC2, which has fixed features and generally better stability; I will be updating the older LC1 less and less - so this issue will not be fixed.

**Comment by joneschrisan** [comment]
That's fair enough but lc2 can't run on my server. Minecraft 1.7.10 Forge 10.13.0.1180

**Comment by CaitlynMainer** [comment]
You need to update forge, that version is ancient.  "10.13.0.1180 Released 07/11/2014 09:21:56 PM"  That's over a year old, I'm shocked *anything* recent works on that...

**Comment by joneschrisan** [comment]
I'm using a few old mods that were never updated past that.

**Comment by AfterLifeLochie** [comment]
You will need at least `1.7.10-10.13.2.1230` to run LC2, because 1230 fixes some serious bugs.

**Comment by joneschrisan** [comment]
Fair enough. I'll check it out then. See if I can get my existing mods to work with it.

**Comment by AfterLifeLochie** [comment]
Assuming this is resolved by updating, and the lack of response.
