### ISSUE TITLE
Plans for different dialing sequences

### ISSUE THREAD

**Issue by joneschrisan** [PC-Logix/LanteaCraft#380]
Are there any plans for different dialing sequences. The current dialing sequence is fine for milkyway and nox gates, but the pegasus gate (and I assume the wraith gate as well) in the cannon have faster dialing sequences which are almost instant and no spinning glyphs.

**Comment by AfterLifeLochie** [comment]
This has already been suggested, and is being worked on in the future features update.  You should consider updating to a newer version of LC.

**Comment by joneschrisan** [comment]
Is there a version after 1.7.10-70?

**Comment by magus1972** [comment]
Yes. It's Lanteacraft 2. I'm on mobile, so I cannot give a link to download.

**Comment by Timmy94W** [comment]
http://cdn.afterlifelochie.net/mods/lanteacraft/unstable.php

These are all unstable builds. Use on your own risk

**Comment by joneschrisan** [comment]
I found them and checked a couple out but lc2 doesn't seem to be able to run on my version. Minecraft 1.7.10, Forge 10.13.0.1180

**Comment by AfterLifeLochie** [comment]
You will need at least `1.7.10-10.13.2.1230` to run LC2, because 1230 fixes some serious bugs.

**Comment by magus1972** [comment]
Why you added Nox and Wraith gates? They weren't in canon. Wasn't it better to add Tollan and Universe gates?

**Comment by joneschrisan** [comment]
That would be good. Did wraith not have their own gates at all? It's been a while I can't quite remember. I'll have to watch the 5 seasons again now.
