### ISSUE TITLE
Index Out Of Bounds Exception with LanteaCraft 15

### ISSUE THREAD

**Issue by Yanniclord** [PC-Logix/LanteaCraft#384]
Ye, so this happened after a while i was using the DHD, then the next time i entered the DHD it crashed immediatly, here the log:

http://pastebin.com/iC0knH8i

**Comment by AfterLifeLochie** [comment]
I don't see any relation between LanteCraft and this crash. Can you please provide all the logs for this session (including the ones in `logs/lanteacraft`) from both the server and client?
