### ISSUE TITLE
The gate isn't working

### ISSUE THREAD

**Issue by tyler6801** [PC-Logix/LanteaCraft#385]
For some odd reason the gate isn't working. I have constructed and powered it correctly but for some reason whenever i enter the symbols it didn't do anything.

**Comment by Zunth5** [comment]
I was recently playing with some friends new to the mod and they had a similar issue. It ended up being that they did not know to press enter after inputting the address (or to press on the center button on the gui). figured I would ask and just rule out the simplest issue first.

**Comment by AfterLifeLochie** [comment]
As above mentioned, have you confirmed you're telling the Stargate to do something?  Is the red button in the DHD red, or grey? Have you tried breaking and replacing the DHD?

-------- Original message --------

**Comment by AfterLifeLochie** [comment]
@tyler6801 , unless you provide some further input, I'm going to close this issue.
