### ISSUE TITLE
When leaving the gate in diamension (chunkloaded) it resets the visual but not the dialed chevrons

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#386]
if you dial a gate and then pause the dialing and you leave the dimension and come back the gate looks like it has no locked chevrons but a computer says he does and if you continue the dialing it starts visual back from 1 but if you had  ex: 4 locked and enter another 5 the gate looks like the it has 5 locked chevrons but it has 9 (when you try to connect it works) 

hope you get what I am trying to say

(version: LC = LanteaCraft-1.7.10-15, dimension: Last Millennium(Extra Utilities)/ overworld  )

![2015-09-14_21 58 03](https://cloud.githubusercontent.com/assets/7773244/9860561/2845ce7c-5b2d-11e5-959f-333966dc46d1.png)
![2015-09-14_21 58 28](https://cloud.githubusercontent.com/assets/7773244/9860560/28437712-5b2d-11e5-90a7-2738cda4803c.png)

![2015-09-14_21 59 57](https://cloud.githubusercontent.com/assets/7773244/9860562/2846c106-5b2d-11e5-8836-da984db86e87.png)
![2015-09-14_21 59 58](https://cloud.githubusercontent.com/assets/7773244/9860577/571126ca-5b2d-11e5-9b58-24411ec697d5.png)

**Comment by AfterLifeLochie** [comment]
This is a client side network desync - it should only affect the current client's display.

I wonder if this works in multiplayer, too; perhaps I need to sit down and investigate more.

-------- Original message --------

**Comment by AfterLifeLochie** [comment]
Should be fixed in commit db8bdac1c6a8ef860bbea1592cb2139ac4404359. Please test in the next build and advise if this isn't the case.

**Comment by lieven121** [comment]
Will test it tomorrow if i dont forget
