### ISSUE TITLE
Ring Transporters Server Lag

### ISSUE THREAD

**Issue by Yanniclord** [PC-Logix/LanteaCraft#387]
Yo guys, only wanted to notify you about the super lag the ring transporters are making when being connected to each other and just waiting to be used. Their lag goes beyond any other entity, so it would be nice to get this fixed, as the TPS fluctuations are aweful. Here a picture:
![unbenannt](https://cloud.githubusercontent.com/assets/5807595/10128334/694286ac-65b1-11e5-9a7f-e25cf4ce4554.png)

So ye, as you see, the update time is beyond any other entity.

(Sorry for having forgotten about the last issue thread i did set up, i didnt find the logs i had so i couldnt reply anymore :/ )

**Comment by AfterLifeLochie** [comment]
This does not definitely indicate a problem with lanteacraft. Please attach your server logs and the profiling information which LC generates so I can look into this at a later date.

-------- Original message --------

**Comment by Yanniclord** [comment]
Here are all the logs: 

core.log : http://pastebin.com/Dd3ySycq
game.log : http://pastebin.com/i13ZPNgJ
performance.log : http://pastebin.com/jFTbwKQ2

**Comment by AfterLifeLochie** [comment]
This still doesn't look like a problem with LC. Can you please show the top tile entities and the top tile entity types, instead of offending chunks?

**Comment by Yanniclord** [comment]
Here are the pics, and you know, i know what i am doing with server side :) You guys are awesome in programming, but server side is my stuff :) Again, here the pics:

![unbenannt](https://cloud.githubusercontent.com/assets/5807595/10167364/83b24a5a-66c8-11e5-8452-17fc3d7fe2fb.png)

![unbenannt2](https://cloud.githubusercontent.com/assets/5807595/10167372/87e23e14-66c8-11e5-8c18-6a4d775de388.png)

**Comment by AfterLifeLochie** [comment]
Based on these screenshots and the profiling data, I don't think this is LanteaCraft. The values shown up in the profiling logs you've provided and from Opis are in microseconds (μs), and the worst values (the last number in the profile log) doesn't nearly get close to a concerning number.

Unless you can provide definitive evidence, as both a developer *and* a past server owner, I'm not going to consider this an issue.

**Comment by Yanniclord** [comment]
Sorry, but i am a 100% sure its LanteaCraft, i dont need to put up any more proof, because if the pictures arent enough, i wont ever be able to satisfy your claim. Both the laggiest chunks (on 7000us) are EXACTLY where BOTH of the Ring Transporters are. LanteaCraft ALSO has the top spot in the laggiest handler of all the mods list. On the Tile Entities tab, EVERY entry in the top is from LanteaCraft, and it mentions the Construction Frame and the Transporter Ring. So, if that isnt proof enough, then i cannot help you, sorry.

**Comment by Yanniclord** [comment]
Here, a more detailed picture if you so will

![unbenannt](https://cloud.githubusercontent.com/assets/5807595/10839077/69b619e6-7ecf-11e5-950d-c0682089325d.png)

If that also isnt enough, then i cannot help it.

**Comment by AfterLifeLochie** [comment]
I have not been able to replicate this behaviour in the development or test environments, so I don't think this is just an issue with LanteaCraft on it's own.
![profile results](http://puu.sh/l4SHd/d5546c1a46.png) 

The `thinkServer` and `thinkClient` methods in TileFrame are empty, so the frame blocks don't (and can't) do any updates, beside the base ones provided by the LCTile system.

Unless you can isolate this to LanteaCraft, I really can't do any more for this issue; it is not replicate-able on my side and I can't see any reason as to why it would occur in the first place.

**Comment by Badcholo** [comment]
Have you tried, with a fresh clean install on server and client with only lanteacraft.
Otherwise it may be a mod compatibility and you need to find out which one.

**Comment by AfterLifeLochie** [comment]
I'm going to assume this isn't an issue, as no response has been received.
