### ISSUE TITLE
Mod breaks, but does not crash in forge 1492

### ISSUE THREAD

**Issue by Badcholo** [PC-Logix/LanteaCraft#388]
forge 1492, i can't make a portal, it won't turn into a portal. The blocks just sit there.
:-(

**Comment by CaitlynMainer** [comment]
Screenshot of your setup?

**Comment by Badcholo** [comment]
![2015-09-30_19 29 40](https://cloud.githubusercontent.com/assets/10932905/10211586/a1a7910a-67a9-11e5-92cd-a1575a06e8c3.png)

**Comment by CaitlynMainer** [comment]
Which version/build of LanteaCraft?

**Comment by Badcholo** [comment]
I am using the latest LanteaCraft-1.7.10-70.jar

**Comment by Badcholo** [comment]
http://www.technicpack.net/modpack/mojangsters.583708

This is my modpack, it worked great with forge 1403
Now with forge 1492, it doesn't seem to work. tested it on my server. 
Testing now on single player

**Comment by Badcholo** [comment]
Ok so it does work fine in SSP, crud, means, i gotta mess with ma server.

**Comment by Badcholo** [comment]
modpack comes with the server ip included.
Ok so i got it to work, but it just wouldn't work in the same spot it was in before.
i went into the wild and it worked fine. I tried to place it in the spot it was before at spawn and it wouldn't  work. very odd. at least it still works, i'm happy. 
want to close this issue?

**Comment by Badcholo** [comment]
I love this mod by the way, i was going to be so sad. Thanks for the quick reply.

**Comment by Badcholo** [comment]
hmm it won't create the portal in the spawn dimension. anywhere. odd.

**Comment by Badcholo** [comment]
sry to have bugged, you, it seems i can place the stargates anywhere but spawn. i'll have to look into what protection plugin is causing this maybe. Is it considered an entity like a mob?

**Comment by Timmy94W** [comment]
As i known stargates are tileEntitys

**Comment by Badcholo** [comment]
I can place a sign and item frames, seems like it should be the same thing. but i can't seem to create the portal. very odd, haven't been able to figure it out.

**Comment by Badcholo** [comment]
Fortress mod also suddently stopped allowing me to use the fortress generator at spawn. it may be factions.

**Comment by Badcholo** [comment]
It seems to be dimension related, cause even if i go outside of the claimed faction spawn area and outside of the spawn region claimed area it just won't let me place it in this dimension. From what i know i have been able to build portals cross dimensions. It just doesn't seem to like this dimension. I will remove test removing some plugins to see what the issue is.

**Comment by Timmy94W** [comment]
maybe there are some conflics with worldguard, but i don't no. I am not a coder for Minecraft mods and i only try to help so much i can, but i doesn't have any experince with this kind of servers or server plugins.

**Comment by Badcholo** [comment]
I did just delete essentials antibuild, maybe it needs it. bleh, hope not.
