### ISSUE TITLE
Why don't the crafting recipes work?

### ISSUE THREAD

**Issue by Badcholo** [PC-Logix/LanteaCraft#389]
The crystals and naquad generator as well as the zmp dont' have crafting recipes.
Is there a fix for this? an update maybe?

**Comment by CaitlynMainer** [comment]
The generator isn't finished enough to have a recipe, same with the ZPM.  I'm not sure about the new builds, but I know the older ones recipes work as long as you have them enabled in the config.

**Comment by Badcholo** [comment]
The generator seems to work just fine with the energy crystal. I just fill it with naquad and place the energy crystal and flip a lever. All the mod seems to need for me is crafting recipes. 
Well it would be nice if the naquad generator used RF and naquad to produce the energy needed for the crystal. Yeah, the crafting receipes are just really bad, I'll come up with some complicated recipes and maybe you'll like em. What is the ZPM supposed to do? or come from?

**Comment by CaitlynMainer** [comment]
You don't craft ZPMs anyway.  They're not fully implemented, and when they are you'll find them very rarely in dungeon loot.  Also, that's really not how Naquadah generators worked in the series... they took Naquadah, and produced power.  Also, with the mod in a total rewrite, there is little reason to suggest recipes right now.

**Comment by Badcholo** [comment]
i didn't know it was in a total rewrite. i thought they stopped working on it completely.

**Comment by CaitlynMainer** [comment]
I'm one of "They" :P  Lochie and I are both fairly busy right now.

**Comment by Badcholo** [comment]
I'm not saying anything bad about it. All i needed was crafting recipes, but i can do that.
Thanks for the reply and updated information. I wasn't pushing for an update or nagging about the mod. I just hadn't seen much activity and that usually means the mod has stopped being worked on.

**Comment by Badcholo** [comment]
You guys doing a total rewrite for 1.8, or will this still be for 1.7.10?
