### ISSUE TITLE
the beam doesn't reach the top ring and apparently you can make the the platform out of anything

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#395]
First nice job the beam looks realy cool even when you pace them with a block off but it doesnt reach the top one
![2015-12-25_11 41 20](https://cloud.githubusercontent.com/assets/7773244/12002386/fa5c6690-aafc-11e5-8acc-820ae8419991.png)

and as also shown on the pic you can make a platform out off any blocks

**Comment by AfterLifeLochie** [comment]
That's strange.

I do know about the visual issues - the beam doesn't correctly figure out which is the top and which is the bottom, and therefore where to start/end rendering.

**Comment by AfterLifeLochie** [comment]
Fixed issue with beam rendering being weird.

Fixed issue where ring activators could be activated if they weren't valid. There was logic to check if the destination was invalid, but not for invalid sources.
