### ISSUE TITLE
cannot create transport rings in MC version 1.7.10

### ISSUE THREAD

**Issue by V497Vesper** [PC-Logix/LanteaCraft#402]
I read about this issue on the wiki and am wondering if this mod has been discontinued or will the transport rings ever be made to work?

**Comment by CaitlynMainer** [comment]
This is to be expected, as the 1.7.10 stable versions have the transport rings disabled in later versions.  The unstable versions http://cdn.afterlifelochie.net/mods/lanteacraft/unstable.php  have transport rings but read the warnings on that page.  Also, "abandoned"  there were a bunch of commits 12 hours ago, and a build around the same time.  Check the Minecraft Forums thread: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1292427-lanteacraft  Specifically the last post by Lochie.
