### ISSUE TITLE
LC2-16 Incorrect gate address results in a hung gate

### ISSUE THREAD

**Issue by UnixRonin** [PC-Logix/LanteaCraft#403]
In build 16, if you intentionally or inadvertently dial an address that does not correspond to any existing gate, the gate dials and locks all nine chevrons, but then freezes there and does not clear.  There doesn't seem to be any way to cancel, and the gate doesn't abort or reset.  It just seems to sit there nearly forever, apparently trying to connect to a non-existent gate.  One assumes it SHOULD fairly quickly be able to determine whether the destination address actually exists, and abort and unlock within some reasonable period of time.  (I would have thought no more than ten to thirty seconds.)  The DHD does not respond while the gate is in this state, so you can't abort the connection from the DHD.

**Comment by AfterLifeLochie** [comment]
It should be instantaneous, as the database kept on the server (or local server) knows which addresses are real or not.

I guess this might have something to do with the way the timeout is handled for the connect instruction; it's quite long so that if the server is overloaded, the gate doesn't time out before the server can load chunks.

**Comment by AfterLifeLochie** [comment]
I have attempted to replicate this, but I see the following:

```
[17:50:13] [Server thread/INFO] [LanteaCraft]: thinkChangeCommand: StargateCommand{CONNECT:200.0, []} => StargateCommand{CONNECT:200.0, []}
[17:50:13] [Server thread/INFO] [LanteaCraft]: No such address found: lc.api.stargate.StargateAddress@3bc05a16
[17:50:13] [Server thread/INFO] [LanteaCraft]: thinkServerDispatchState: StargateCommand{CONNECT:200.0, []}
[17:50:23] [Server thread/INFO] [LanteaCraft]: thinkChangeCommand: StargateCommand{CONNECT:200.0, []} => [none]
```

I can see that after 10 seconds, the Stargate gives up connecting (it goes from Command ```CONNECT`` to ```none```).

Can you please try and repeat this on your end, but watch out for these logging entries? Also, check your TPS rate, too.

**Comment by UnixRonin** [comment]
I'll retest as soon as I get an opportunity.  Are there any particular logging settings I need to turn on?

**Comment by AfterLifeLochie** [comment]
No - so long as you have a console, you should see the logs.

If not, they'll appear in one of the log files; from memory it should appear in `game.log` under the LC folder - if not, it should show up in forge logs.

**Comment by mrdrewlego** [comment]
This has also happened to me and the only way to cancel the hung gate is to destroy a block on the actual gate.

**Comment by AfterLifeLochie** [comment]
I'm struggling to replicate this in development.

Can someone please provide me some logs so I could figure out what is going on here?

**Comment by HydrantHunter** [comment]
As already mentioned, the gate does appear to hang for about 6-10 seconds after pressing the orange button, but always becomes responsive for me after that time has passed (I'm guessing this is related to issue #372 which is closed).

Even after the timeout, though, the gate may appear to be hung as all chevrons are lit and the orange button won't connect/disconnect or clear the chevrons (which I believe was the behavior in 1.7.10-70)

@UnixRonin and @mrdrewlego:  When the gate is in this state does the backspace key clear the chevrons for you (after the timeout has passed, of course)?

**Comment by UnixRonin** [comment]
just to double-triple-and-a-bit confirm, we're still working against LC2 build 16, right?  There is no build 17 available yet?

That assumption, well, assumed:

I removed LC build 70 from my test server, cleaned, restarted with no gates, added LC2 build 16, restarted again, built a single gate, and attempted to dial ABCDEFGHI.  The gate hung in a state with all chevrons lit but nothing happening for over 90 seconds before I ESC'd out of the DHD interface.

I then reconnected to the DHD and tried backspacing.  I was able to erase the ABCDEFGHI address that was still present in the DHD, unlocking chevrons as I went.

This is the resulting log:

[DEBUG] Creating container lc.container.ContainerStargate
[DEBUG] Handling GUI request: id 1
[DEBUG] Creating container lc.container.ContainerDHD
[DEBUG] Saving profiling data...
[DEBUG] Saved profiling data to disk.
[DEBUG] thinkChangeCommand: [none] => StargateCommand{SPIN:20.0, [A,]}
[DEBUG] thinkServerDispatchState: StargateCommand{SPIN:20.0, [A,]}
[DEBUG] thinkChangeCommand: StargateCommand{SPIN:20.0, [A,]} => StargateCommand{ENGAGE:5.0, []}
[DEBUG] thinkServerDispatchState: StargateCommand{ENGAGE:5.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{ENGAGE:5.0, []} => StargateCommand{SPIN:20.0, [B,]}
[DEBUG] thinkServerDispatchState: StargateCommand{SPIN:20.0, [B,]}
[DEBUG] thinkChangeCommand: StargateCommand{SPIN:20.0, [B,]} => StargateCommand{ENGAGE:5.0, []}
[DEBUG] thinkServerDispatchState: StargateCommand{ENGAGE:5.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{ENGAGE:5.0, []} => StargateCommand{SPIN:20.0, [C,]}
[DEBUG] thinkServerDispatchState: StargateCommand{SPIN:20.0, [C,]}
[DEBUG] thinkChangeCommand: StargateCommand{SPIN:20.0, [C,]} => StargateCommand{ENGAGE:5.0, []}
[DEBUG] thinkServerDispatchState: StargateCommand{ENGAGE:5.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{ENGAGE:5.0, []} => StargateCommand{SPIN:20.0, [D,]}
[DEBUG] thinkServerDispatchState: StargateCommand{SPIN:20.0, [D,]}
[DEBUG] thinkChangeCommand: StargateCommand{SPIN:20.0, [D,]} => StargateCommand{ENGAGE:5.0, []}
[DEBUG] thinkServerDispatchState: StargateCommand{ENGAGE:5.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{ENGAGE:5.0, []} => StargateCommand{SPIN:20.0, [E,]}
[DEBUG] thinkServerDispatchState: StargateCommand{SPIN:20.0, [E,]}
[DEBUG] thinkChangeCommand: StargateCommand{SPIN:20.0, [E,]} => StargateCommand{ENGAGE:5.0, []}
[DEBUG] thinkServerDispatchState: StargateCommand{ENGAGE:5.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{ENGAGE:5.0, []} => StargateCommand{SPIN:20.0, [F,]}
[DEBUG] thinkServerDispatchState: StargateCommand{SPIN:20.0, [F,]}
[DEBUG] thinkChangeCommand: StargateCommand{SPIN:20.0, [F,]} => StargateCommand{ENGAGE:5.0, []}
[DEBUG] thinkServerDispatchState: StargateCommand{ENGAGE:5.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{ENGAGE:5.0, []} => StargateCommand{SPIN:20.0, [G,]}
[DEBUG] thinkServerDispatchState: StargateCommand{SPIN:20.0, [G,]}
[DEBUG] thinkChangeCommand: StargateCommand{SPIN:20.0, [G,]} => StargateCommand{ENGAGE:5.0, []}
[DEBUG] thinkServerDispatchState: StargateCommand{ENGAGE:5.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{ENGAGE:5.0, []} => StargateCommand{SPIN:20.0, [H,]}
[DEBUG] thinkServerDispatchState: StargateCommand{SPIN:20.0, [H,]}
[DEBUG] thinkChangeCommand: StargateCommand{SPIN:20.0, [H,]} => StargateCommand{ENGAGE:5.0, []}
[DEBUG] thinkServerDispatchState: StargateCommand{ENGAGE:5.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{ENGAGE:5.0, []} => StargateCommand{SPIN:20.0, [I,]}
[DEBUG] thinkServerDispatchState: StargateCommand{SPIN:20.0, [I,]}
[DEBUG] thinkChangeCommand: StargateCommand{SPIN:20.0, [I,]} => StargateCommand{ENGAGE:5.0, []}
[DEBUG] thinkServerDispatchState: StargateCommand{ENGAGE:5.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{ENGAGE:5.0, []} => [none]
[DEBUG] thinkChangeCommand: [none] => StargateCommand{CONNECT:200.0, []}
[DEBUG] No such address found: lc.api.stargate.StargateAddress@4bb66085
[DEBUG] thinkServerDispatchState: StargateCommand{CONNECT:200.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{CONNECT:200.0, []} => [none]
[DEBUG] Saving profiling data...
[DEBUG] Saved profiling data to disk.
[DEBUG] Saving profiling data...
[DEBUG] Saved profiling data to disk.
[DEBUG] Saving profiling data...
[DEBUG] Saved profiling data to disk.
[DEBUG] Handling GUI request: id 1
[DEBUG] Creating container lc.container.ContainerDHD
[DEBUG] thinkChangeCommand: [none] => StargateCommand{DISENGAGE:5.0, []}
[DEBUG] thinkServerDispatchState: StargateCommand{DISENGAGE:5.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{DISENGAGE:5.0, []} => [none]
[DEBUG] thinkChangeCommand: [none] => StargateCommand{DISENGAGE:5.0, []}
[DEBUG] thinkServerDispatchState: StargateCommand{DISENGAGE:5.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{DISENGAGE:5.0, []} => StargateCommand{DISENGAGE:5.0, []}
[DEBUG] thinkServerDispatchState: StargateCommand{DISENGAGE:5.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{DISENGAGE:5.0, []} => StargateCommand{DISENGAGE:5.0, []}
[DEBUG] thinkServerDispatchState: StargateCommand{DISENGAGE:5.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{DISENGAGE:5.0, []} => StargateCommand{DISENGAGE:5.0, []}
[DEBUG] thinkServerDispatchState: StargateCommand{DISENGAGE:5.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{DISENGAGE:5.0, []} => StargateCommand{DISENGAGE:5.0, []}
[DEBUG] thinkServerDispatchState: StargateCommand{DISENGAGE:5.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{DISENGAGE:5.0, []} => StargateCommand{DISENGAGE:5.0, []}
[DEBUG] thinkServerDispatchState: StargateCommand{DISENGAGE:5.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{DISENGAGE:5.0, []} => StargateCommand{DISENGAGE:5.0, []}
[DEBUG] thinkServerDispatchState: StargateCommand{DISENGAGE:5.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{DISENGAGE:5.0, []} => StargateCommand{DISENGAGE:5.0, []}
[DEBUG] thinkServerDispatchState: StargateCommand{DISENGAGE:5.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{DISENGAGE:5.0, []} => StargateCommand{DISENGAGE:5.0, []}
[DEBUG] Skipping command StargateCommand{DISENGAGE:5.0, []}, invalid state.
[DEBUG] thinkChangeCommand: StargateCommand{DISENGAGE:5.0, []} => StargateCommand{DISENGAGE:5.0, []}
[DEBUG] Skipping command StargateCommand{DISENGAGE:5.0, []}, invalid state.
[DEBUG] thinkChangeCommand: StargateCommand{DISENGAGE:5.0, []} => StargateCommand{DISENGAGE:5.0, []}
[DEBUG] Skipping command StargateCommand{DISENGAGE:5.0, []}, invalid state.
[DEBUG] thinkChangeCommand: StargateCommand{DISENGAGE:5.0, []} => StargateCommand{DISENGAGE:5.0, []}
[DEBUG] Skipping command StargateCommand{DISENGAGE:5.0, []}, invalid state.
[DEBUG] thinkChangeCommand: StargateCommand{DISENGAGE:5.0, []} => StargateCommand{DISENGAGE:5.0, []}
[DEBUG] Skipping command StargateCommand{DISENGAGE:5.0, []}, invalid state.
[DEBUG] thinkChangeCommand: StargateCommand{DISENGAGE:5.0, []} => StargateCommand{DISENGAGE:5.0, []}
[DEBUG] Skipping command StargateCommand{DISENGAGE:5.0, []}, invalid state.
[DEBUG] thinkChangeCommand: StargateCommand{DISENGAGE:5.0, []} => StargateCommand{DISENGAGE:5.0, []}
[DEBUG] Skipping command StargateCommand{DISENGAGE:5.0, []}, invalid state.
[DEBUG] thinkChangeCommand: StargateCommand{DISENGAGE:5.0, []} => [none]
[DEBUG] thinkChangeCommand: [none] => StargateCommand{DISENGAGE:5.0, []}
[DEBUG] Skipping command StargateCommand{DISENGAGE:5.0, []}, invalid state.
[DEBUG] thinkChangeCommand: StargateCommand{DISENGAGE:5.0, []} => [none]
[DEBUG] Default configuration modified. Saving it...
[DEBUG] Default configuration committed.

**Comment by AfterLifeLochie** [comment]
```
[DEBUG] thinkServerDispatchState: StargateCommand{ENGAGE:5.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{ENGAGE:5.0, []} => [none]
[DEBUG] thinkChangeCommand: [none] => StargateCommand{CONNECT:200.0, []}
[DEBUG] No such address found: lc.api.stargate.StargateAddress@4bb6608
[DEBUG] thinkServerDispatchState: StargateCommand{CONNECT:200.0, []}
[DEBUG] thinkChangeCommand: StargateCommand{CONNECT:200.0, []} => [none]
```

So if I'm not mistaken: 
1. The Stargate connects
2. The address manager indicates the `StargateAddress` is invalid
3. The Stargate goes idle, BUT:
  * You expect the DHD to visually go idle too; and
  * You expect the Stargate to clear all chevrons
4. You can continue to use the Stargate afterwards.

**Comment by UnixRonin** [comment]
Looking at the logs, yeah, it gets an invalid address and goes idle.  But it doesn't reset, and it's not obvious that that's what's happened unless you're reading the logs.  And trying to disconnect by hitting the orange button again doesn't do anything, because it can't disconnect when it isn't connected in the first place.  It's not obvious that this is what's going on, because with the button still lit the DHD *LOOKS* as though it's still trying to connect.  So it seems this isn't a *functional bug* so much as a failure to communicate a connection failure back to the user.

What I would expect to happen (and what I remember happening from the series) is that if dialling fails because the address doesn't exist, the gate resets and the chevrons all unlock.  Another behavior that would convey the result is if the orange button lights when hit, then goes dark again after a couple of seconds when the gate fails to connect.

[KA-CHUNK .... pause ... KA-CHUNK]
"Oh, crap.  This address isn't working."

Instead of:
[KA-CHUNK]
...
...
...
[tap, tap] "Hey, is this thing on?"

**Comment by AfterLifeLochie** [comment]
Okay, I see what you mean now.

It is more of a cosmetic issue (ie, it doesn't technically impede operation) but it should be fixed, because it's very clearly misleading.

**Comment by mrdrewlego** [comment]
I cannot currently check to see if this is the case but when I have access to this mod again I will be sure to see if it is this. Also does this mod add structures into the world? I do notice a ton of spam of stargate structures spawning in the log after a crash and want to know if it is this mod that adds any structures?

**Comment by AfterLifeLochie** [comment]
> the gate resets and the chevrons all unlock

This now happens and is fixed as of commit e306681e04956f4007af56255ec350ff6effb8ad.

> I do notice a ton of spam of stargate structures spawning in the log after a crash and want to know if it is this mod that adds any structures

Don't hijack issue threads. This is issue #414.

**Comment by UnixRonin** [comment]
Thank you Lochie.
Is there a snapshot build that I can download with this commit, or would I need to fetch and build it myself?  (And if so, can anyone point me at instructions for how to set up the build environment?)

**Comment by AfterLifeLochie** [comment]
Build 19 has the fix.

**Comment by UnixRonin** [comment]
And it's now on the download page.  Thanks Lochie!  You and Michiyo rock!
