### ISSUE TITLE
Iris not working

### ISSUE THREAD

**Issue by joneschrisan** [PC-Logix/LanteaCraft#411]
Iris on milkyway gate does not seem to work.

**Comment by TARDIStraveler15** [comment]
How do you even get the iris/shield?

**Comment by CaitlynMainer** [comment]
You don't they're not fully implemented.

**Comment by ver1tatem** [comment]
Until it is implemented I'm going to keep using Advanced Repulsion forcefields to block entrances. Reminds me of the Atlantis iris. Hope that helps someone 
![screen shot 2016-01-29 at 2 47 19 pm](https://cloud.githubusercontent.com/assets/16630490/12686382/4c60aec8-c697-11e5-9d87-13eb986bd0ff.png)
![screen shot 2016-01-29 at 2 47 28 pm](https://cloud.githubusercontent.com/assets/16630490/12686383/4c63ae84-c697-11e5-947b-a4d26dd8320b.png)

**Comment by AfterLifeLochie** [comment]
The iris isn't implemented, hence it's not a craft-able item.

**Comment by AfterLifeLochie** [comment]
It now functions as of f361f84d32bfa446fc10e915140ef2c7c5bd7f56.
