### ISSUE TITLE
LC2-19: In ComputerCraft, calling closeIris() closes then reopens the iris

### ISSUE THREAD

**Issue by HydrantHunter** [PC-Logix/LanteaCraft#416]
### Submission checklist
- [x] Check that you are running the latest recommended version of LanteaCraft.
- [X] Check that the issue isn't a known problem already (https://github.com/PC-Logix/LanteaCraft/issues).
- [ ] Check that you can repeat this issue with just LanteaCraft installed.  NOTE: ComputerCraft also required.
### Expected behavior
1. When calling closeIris() the mechanical iris should close and stay closed
2. When calling closeIris() the energy iris should activate
### Actual behavior
1. When calling closeIris() the mechanical iris closes, then reopens
2. When calling closeIris() the energy iris appears to do nothing
### Steps to reproduce

Install an iris in the stargate, then start the Lua console and wrap the gate, then call e.g. gate.closeIris()
### System information
- MinecraftForge version: 10.13.4.1558
- LanteaCraft version: LC2-19
- Logs: no logs

**Comment by AfterLifeLochie** [comment]
This is because `thinkServerIris` overrides the state of the Iris.

What happens if you apply a redstone signal to the Stargate, then use `openIris()` method?

**Comment by HydrantHunter** [comment]
Applying a redstone signal to anything other than the base has no effect.  Applying a redstone signal to the StargateBase closes the iris immediately.  Calling `openIris()` while the redstone signal is applied causes the iris to open then close again.

**Comment by AfterLifeLochie** [comment]
Okay, so `thinkServerIris`  is definitely overstamping the state.

**Comment by lieven121** [comment]
also the iris doesn't work unless I open the stargate gui once is this related to this or is this a other problem?

**Comment by AfterLifeLochie** [comment]
I don't quite understand, but it sounds like a separate issue.

**Comment by lieven121** [comment]
yeah I was confused 
I am now thinking it has something to do with #417 srr for the "false" post

**Comment by AfterLifeLochie** [comment]
This should now be fixed through 1236e85720ba0d42d1bc3688c7ae1a27f60f7153.

If you close the iris using redstone or computer, it will only re-open if you deactivate whatever activated it first (ie, if you used `stargate.closeIris()`, it won't open (even on redstone change) until you call `stargate.openIris()`).

**Comment by HydrantHunter** [comment]
I like the activation/deactivation priority concept - thank you!

**Comment by AfterLifeLochie** [comment]
This is really only a temporary work around since the Logic system doesn't allow you to pick what input(s) you want the gate to observe (it's always been on the other tab).

At some stage I'll allow you to select exactly what inputs trigger what actions, but for now the `IOControlBaton` workaround seems to make the functionality more regular and at least usable.
