### ISSUE TITLE
LC2-19: Iris does not render correctly after player leaves/dies

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#417]
### Submission checklist
- [x] Check that you are running the latest recommended version of LanteaCraft.
- [x] Check that the issue isn't a known problem already (https://github.com/PC-Logix/LanteaCraft/issues).
- [x] Check that you can repeat this issue with just LanteaCraft installed.
### Expected behavior

the iris stays 
### Actual behavior

the iris disappears when dying / relogging
### Steps to reproduce

build a stargate 
activate the iris 
(set world spawn)
kill yourself or relog
### System information
- MinecraftForge version: _10.13.4.1614_
- LanteaCraft version: _19_

some other things:
is it normal that the gate has the texture of the ring instead of the textures in the file (LanteaCraft-1.7.10-19.jar\assets\pcl_lc\textures\fx)

and I would like to ask could you make that the gate fills with "invisible blocks" that are solid (but maybe as think as the gate) so you cant go trough a gate with a closed iris

and will there be a get IrisState function (opened or closed)

**Comment by AfterLifeLochie** [comment]
This issue is related to the network desync problems in issue #386.

The texture is known to be broken, so not an issue.

There is provision for pathing blocking, but it will be done without using blocks.

A `getIrisState` function will be exposed, but for now you can just use `openIris` and `closeIris`, if the Stargate already has the iris closed then nothing will happen.

**Comment by AfterLifeLochie** [comment]
Should be fixed in commit db8bdac1c6a8ef860bbea1592cb2139ac4404359. Please test in the next build and advise if this isn't the case.

**Comment by lieven121** [comment]
No still a problem 
but now you have to open the gui first

**Comment by AfterLifeLochie** [comment]
OK, I'll investigate more. Thanks. :)

**Comment by lieven121** [comment]
I found this is because the tile enity from the server and the client are out of sync 
The client render looks at the inventory of the tile entity of the client
but the inventory of the tile entity only gets send to the client when opening the gui


I've been looking trough the code but still havent found a solution (I am fairly new to java)
