### ISSUE TITLE
LC2-19: irisOpened and irisClosed events triggered at start instead of completion

### ISSUE THREAD

**Issue by HydrantHunter** [PC-Logix/LanteaCraft#418]
### Submission checklist

- [X] Check that you are running the latest recommended version of LanteaCraft.
- [X] Check that the issue isn't a known problem already (https://github.com/PC-Logix/LanteaCraft/issues).
- [ ] Check that you can repeat this issue with just LanteaCraft installed.  NOTE: ComputerCraft also required.

### Expected behavior

irisOpened and irisClosed events trigger when the event is completed (when the iris is fully open or closed)

### Actual behavior

irisOpened and irisClosed events are triggered at the start of the action instead of upon completion (eg irisOpened is triggered when the iris starts opening, instead of when it's fully open).

### Steps to reproduce

Close or open the iris on a gate while monitoring the events generated by the gate - you'll see the events are triggered as the action starts, instead of up on completion.

### System information

- MinecraftForge version: 10.13.4.1558
- LanteaCraft version: LC2-19
- Logs: no logs

**Comment by AfterLifeLochie** [comment]
There's no current provision in code for doing event callbacks after something happens, but I'll see what I can do.

**Comment by AfterLifeLochie** [comment]
This should be addressed in d9d00154f593bea44d9e587e0616a9dda94b84a8. You'll now get `irisOpening`, `irisOpened`, `irisClosing` and `irisClosed` at (approximately) the same time as the client -- remembering that your network latency will have some factor as well. 🎱
