### ISSUE TITLE
LC2-21: Transporter Rings incorrectly categorized under Stargates feature set

### ISSUE THREAD

**Issue by DraksterAU** [PC-Logix/LanteaCraft#419]
Disabling Stargate in Config disables ring platform at present but not the activator (it should disable neither)
I'm looking into trying to use specific portions of Lanteacraft (because it has some nice features but I cant use all of them)... but it looks like I have to use gates if I want transport rings.

Reason I am avoiding gates is I have heavily modified SGCraft stargate behaviour for use with our server... and your license.md dictates that you do not wish to see LC source modified.

### Expected behavior

Disabling the STARGATE config setting should not disable the ring platform

### Actual behaviour

Disabling the STARGATE config setting does disable the ring platform

### Steps to reproduce

Install Lanteacraft & Disable STARGATE in the config file.

### System information

- MinecraftForge version: 1614.
- LanteaCraft version: LC2-21
- Logs: Not relavent, this is not throwing errors.

**Comment by lieven121** [comment]
I think currently he means "transportation" with STARGATE

**Comment by DraksterAU** [comment]
Well that sucks :P

**Comment by lieven121** [comment]
maybe he will change that and if its just for survival why don't you just not use it and else with some mods out there you can even disable the crafting recipes

**Comment by DraksterAU** [comment]
Lochie made the modular config system for a reason mate.... So admins could do exactly what I'm trying to do.

Please let him do the commenting.

**Comment by lieven121** [comment]
was just trying to help you find a tmp solution

**Comment by DraksterAU** [comment]
Sorry your right... Thanks for the tip.

**Comment by AfterLifeLochie** [comment]
> Disabling Stargate in Config disables ring platform at present but not the activator (it should disable neither)

This is technically true; they're not Stargates, they should be under `MACHINE` or something like that. Or even their own option, but I don't know if I want to do that.

> heavily modified SGCraft stargate behaviour

Can you elaborate on this? I have been toying with the idea of allowing Stargate behaviours to be customized (not via Java, fwiw).

> Should be all or none

This is true, I grouped them wrong and never noticed.

> you can even disable the crafting recipes

There are no recipes for the activators or ring blocks, so unless you add them yourself they won't work.

> So admins could do exactly what I'm trying to do.

It wasn't aimed for this exact purpose, but having the ability to disable some unwanted features is a good thing.

**Comment by DraksterAU** [comment]
Hi Lochie,

Please categories them under something more specific, if someone wanted to use naquadah generators and transport rings be disabled it would be cool to be able to split the difference.
I'd almost put them as being a main feature, like stargates.

Behaviours, in no particular order:

1. Dimension mapping; Virtually mapping all dimensions with coordinates in a fake "space dimension" (in the case of users who use the WarpDrive mod this could be the WarpDrive space dimension).

Power costs are based on this. Each dimension had a radius in the space dimension and same planet wormholes are calculated with a power discount of 90%.

2. Galaxy mapping. This is done with all dimensions being considered part of the same Galaxy if their coordinates in the virtual universe fall within the radius of the Galaxy. A "discount" to standard power costs is set to make it easier to travel around the same Galaxy. Ours is 50%

3. Kino style address finder, so that planets for the Galaxy a player is in can have their gate addresses displayed. On our server this only scans a 32x32 block radius from the world spawn to minimise server la as that is where we have a protected spawn with a powered gate

4. Custom dialling rules.
-  I've set up so out "starting area world" can only dial the spawn world in each Galaxy or another gate on the same world it is on
- midway style restrictions. We have a midway dimension and rules for both the Pegasus gate and milky way gate that match canon on the show ( can only dial earth or Atlantis )

5. 8th and 9 chevron upgrades for gates, to allow a gate to do either intergalactic or "stupidly large destiny style" distances.

I've also made up a gdo system and a few other bits and bobs to allow players to modify gate behaviour with computers, you can see the repo at https://GitHub.com/StargateMC/sgcraft-modded

I understand these changes might not be what your wanting to do and specific to what I want on our server.. I've just being trying to expand on the canon-ish style server idea.

Excuse my horrible Java if you do look at the code... I go for working not pretty haha

Regards

DraksterAU

**Comment by DraksterAU** [comment]
One little side note.. We are currently experimenting with hologram maps from open computers for worlds/galaxies. Is quite interesting!

**Comment by AfterLifeLochie** [comment]
Changed in commit f6f3d15d4a3d6c9d7054235cb43df2d24c91859e, but something will need to be done in  the future I think.

**Comment by DraksterAU** [comment]
Much appreciated Lochie!
Will install lantea craft as soon as I've tested it on our server :)
