### ISSUE TITLE
LC2-21: Issues with block render state not updating

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#422]
- [x] Check that you are running the latest recommended version of LanteaCraft.
- [x] Check that the issue isn't a known problem already (https://github.com/PC-Logix/LanteaCraft/issues).
- [x] Check that you can repeat this issue with just LanteaCraft installed.
### Expected behavior

if you break the base all the blocks should be visible 
### Actual behavior

it deforms but some blocks remain invisible 

as soon as there is a chunk update the blocks render again
### Steps to reproduce

place a gate over a chunk border (at least one block between border and base
break the base
### System information
- MinecraftForge version: 10.13.4.1614 
- LanteaCraft version: 21
  ![2016-03-21_16 28 52](https://cloud.githubusercontent.com/assets/7773244/13924982/ce5cb256-ef86-11e5-99a0-9653dc966ebb.png)

![2016-03-21_16 29 18](https://cloud.githubusercontent.com/assets/7773244/13924986/d07cbe50-ef86-11e5-8431-51dbff51bc74.png)

![2016-03-21_16 30 46](https://cloud.githubusercontent.com/assets/7773244/13924991/d4fa8ae8-ef86-11e5-80af-f3c423838e51.png)

**Comment by lyqyd** [comment]
Please make sure that screenshots used to demonstrate an issue are taken with the subject properly illuminated. The second screenshot is too dark to clearly see, and the third looks entirely black (at least on my phone). It would be helpful if you could re-take these screenshots during daylight hours in-game.

Are the cutoff planes also chunk boundaries?

**Comment by lieven121** [comment]
Yep at the chunk boundary starts the invisible part srr for poor lighting if its necessary  i will retake them tomorrow and the 3th is just a note that that there the chunk ends

**Comment by AfterLifeLochie** [comment]
Can you please give me the in-game coordinates from these screenshots?

If you take screenshots in the future, you **must** include the F3 debug screen; some issues are to do with coordinates, so.

**Comment by lieven121** [comment]
Currently my pc is off but i can provide them tomorrow or on a other issue i reportted the f3 is there and it isnt that far away from where i took the screenshots

**Comment by AfterLifeLochie** [comment]
I need the exact working coordinates, close enough isn't good enough. If it's a bug to do with one particular X/Y/Z configuration, I don't want to be hunting around for which coordinates it happens at.

**Comment by lieven121** [comment]
And as my testing i did this in multiple chunks (sometimes 6 chunks apart) so i gues this should work anywhere

**Comment by lieven121** [comment]
I can confim that's its 99% sure not postion bound (I mean not where x y) the only condition is that ist on a chunk border and the base cant touch the border
