### ISSUE TITLE
LC2-21: Gates generating two events for every action

### ISSUE THREAD

**Issue by HydrantHunter** [PC-Logix/LanteaCraft#424]
### Submission checklist

- [X] Check that you are running the latest recommended version of LanteaCraft.
- [X] Check that the issue isn't a known problem already (https://github.com/PC-Logix/LanteaCraft/issues).
- [ ] Check that you can repeat this issue with just LanteaCraft installed.  NOTE: ComputerCraft also required.

### Expected behavior

Gates should generate a single event for each action (e.g. connect)

### Actual behavior

Gates are generating two events for each action

### Steps to reproduce

Monitor gate events and do pretty much anything - e.g. start dialing with a DHD - each chevron dialed will generate two "spinToGlyph" and two "chevronEngaged" events.

### System information

- MinecraftForge version: 10.13.4.1558
- LanteaCraft version: LC2-21
- Logs: no logs

**Comment by AfterLifeLochie** [comment]
Can you please attach the working logs from this?

**Comment by HydrantHunter** [comment]
Closing this issue - it was my fault.  I had the gate connected both directly and via modem.  Apologies for the bad report.
