### ISSUE TITLE
Suggestion - Redstone Activated Rings

### ISSUE THREAD

**Issue by DraksterAU** [PC-Logix/LanteaCraft#427]
If possible, Can you please implement a way to activate rings without the handheld device...?

My understanding is that they now require the activator to be used and there are no other methods.

Sorry if this is planned - if there is a roadmap point me in the direction of it and close the issue :)

**Comment by lieven121** [comment]
or maybe also cc controlled

**Comment by DraksterAU** [comment]
Redstone can be activated by computer?

**Comment by HydrantHunter** [comment]
Yes, redstone can be activated by computer.  I believe what lieven121 was suggesting, though, was the ability to control the rings with specific methods for computers.

**Comment by lieven121** [comment]
Yeah but that has it limits and if he makes it so you have to chose or can block the way the rings can be activated computer is more secure and he could give a pc more control ex: tp up, tp down , skip 2

**Comment by Cronosus** [comment]
i think, this is already requested by me
#109
