### ISSUE TITLE
LC2.21 - Stargate particles when dialing

### ISSUE THREAD

**Issue by Cronosus** [PC-Logix/LanteaCraft#431]
When dialing, there are rendered some particles... mabe something from debug?
![2016-03-25_00 11 59](https://cloud.githubusercontent.com/assets/5349950/14054824/afed2cca-f2dc-11e5-9c80-a8a4002ca5ad.png)

**Comment by lieven121** [comment]
This is normal they are dust particles

**Comment by AfterLifeLochie** [comment]
This is an intended feature.

It's also a duplicate ticket, but I can't find the original place it was brought up. I imagine it was inside another ticket, but I can't find it.
