### ISSUE TITLE
Decorator crash On server

### ISSUE THREAD

**Issue by Cronosus** [PC-Logix/LanteaCraft#434]
### Submission checklist
- [x] Check that you are running the latest recommended version of LanteaCraft.
- [x] Check that the issue isn't a known problem already (https://github.com/PC-Logix/LanteaCraft/issues).
- [x] Check that you can repeat this issue with just LanteaCraft installed.
### Steps to reproduce

Just insert Decorator inside crafting table
### System information
- MinecraftForge version: KCauldron:1.7.10-1614.188
- LanteaCraft version: 21
- Logs: http://cronos.wz.cz/mc/lc/fml-server-3.log
- Crash: http://pastebin.com/BPjukBLa

**Comment by AfterLifeLochie** [comment]
I'm inclined to believe this isn't an issue as LanteaCraft is built against Forge 10.13.2.1230 and operates fine in normal conditions.

I have no idea what version of Forge is being implemented by KCauldron, but it does not appear to be compatible with Forge 10.13.2.1230.=

**Comment by Cronosus** [comment]
kcauldron with same forge as name.. forge 10.13.4.1614

**Comment by Cronosus** [comment]
tried ONLY LC, build 21
crash: http://cronos.wz.cz/mc/lc/crash-2016-04-25_17.58.06-server.txt
log: http://cronos.wz.cz/mc/lc/latest.log

server:
KCauldron-1.7.10-1614.201
with forge 10.13.4.1614

**Comment by lyqyd** [comment]
Have you tried running it under whatever version of KCauldron uses Forge version 10.13.2.1230? It is important to ensure that you are using compatible versions of Forge, and with different revision numbers (10.13.2 vs 10.13.4), it is unlikely that full compatibility exists between the two.

**Comment by Cronosus** [comment]
i can't use lower version, because i have mods which requires latest version of kcauldron

**Comment by lyqyd** [comment]
You could try building the mod against Forge 10.13.4.1614 yourself, following the [build instructions](https://github.com/PC-Logix/LanteaCraft/blob/master/BUILD.md). It doesn't sound like Lochie is looking at changing to build against a newer version of Forge any time soon. This is a version incompatibility and not a bug, so your options are to build it on your own or to wait on the possibility (which may or may not happen) that LC starts to be built against a version of Forge compatible with the version you want to use.

**Comment by Cronosus** [comment]
these instructions not helping me, i tried already to build some mods myself, but i can't correctly setup eclipse.. :(
and anyway, i dont know if is problem with forge or kcauldron...

**Comment by Cronosus** [comment]
here info from thermos server developer

https://github.com/CyberdyneCC/Thermos/issues/389#issuecomment-223763644

> ![bf77b974-2a4c-11e6-8b80-3c28abdb7e92](https://cloud.githubusercontent.com/assets/5349950/15800721/6347bce6-2a81-11e6-9f9d-19e7546252aa.png)
> This mod is using methods only available clientside. Not a problem on our end.
> You might have installed the version intended for singleplayer, the developer might've made a mistake, or this mod was only designed with singleplayer in mind.
