### ISSUE TITLE
Lanteacraft not handling player disconnection well

### ISSUE THREAD

**Issue by Dijkstra1-zz** [PC-Logix/LanteaCraft#436]
### Expected behavior

Not crash when server says someone has disconnected when they have.
### Actual behavior

Sever crashes when sever says someone disconnect and they have not. 
### Steps to reproduce

Log in to a server with lanteacraft a wait a minute to see if you see a message saying that you have disconnect, and you still online. It does not happen often, but is still annoying. 
### System information
- MinecraftForge version: forge-1.7.10-10.13.4.1614-1.7.10
- LanteaCraft version: LanteaCraft-1.7.10-21
- Logs: [crash-2016-04-13_00.52.26-server.txt](https://github.com/PC-Logix/LanteaCraft/files/217057/crash-2016-04-13_00.52.26-server.txt)

**Comment by AfterLifeLochie** [comment]
Fixed in commit e363a4fd014bd765e8bec61ab09f490fdddb4dfb.
