### ISSUE TITLE
Iris? 

### ISSUE THREAD

**Issue by dodhod** [PC-Logix/LanteaCraft#445]
_Thank you for reporting an issue with LanteaCraft. Please fill out this template when submitting your report - thank you!_
### Submission checklist
- [yes ] Check that you are running the latest recommended version of LanteaCraft.
- [yes ] Check that the issue isn't a known problem already (https://github.com/PC-Logix/LanteaCraft/issues).
- [ yes] Check that you can repeat this issue with just LanteaCraft installed.
### Expected behavior

_Write your expected behavior here._
Have the actual irises been added yet, if so how do I use them
### Actual behavior

_Write what you have observed here._
### Steps to reproduce

_Write any steps you have taken to reproduce the issue here._
### System information
- MinecraftForge version: _write your version here_
- LanteaCraft version: _write your version here_
- Logs: _include any links to your log files here_

**Comment by lieven121** [comment]
Yes it has been added (only mechanical)
It works by placing the iris module in the gate 
And apply a redstone singal to open and close
Cc support doesnt work

**Comment by dodhod** [comment]
Thanks, could you link the version with the iris. Thanks again

**Comment by lieven121** [comment]
http://cdn.afterlifelochie.net/mods/lanteacraft/
Just download the latest

**Comment by dodhod** [comment]
How do you repair the iris so it's at 21 'health'?

**Comment by lieven121** [comment]
you don't need to the durability doesn't work yet as far as I know

**Comment by dodhod** [comment]
Ah, only because I can fly through it, thought it would be solid :P

**Comment by lieven121** [comment]
you can come trough an active gate with iris or just fly trough a iris 
because the iris isn't solid yet (is requested) it only blocks you from coming from another gate

**Comment by dodhod** [comment]
Ah, thank you! Can now close this topic. :)
