### ISSUE TITLE
LC2-22: Stargate computer methods not functioning

### ISSUE THREAD

**Issue by lieven121** [PC-Logix/LanteaCraft#449]
*Thank you for reporting an issue with LanteaCraft. Please fill out this template when submitting your report - thank you!*

### Submission checklist

- [ x] Check that you are running the latest recommended version of LanteaCraft.
- [x ] Check that the issue isn't a known problem already (https://github.com/PC-Logix/LanteaCraft/issues).
- [ x+ computecraft] Check that you can repeat this issue with just LanteaCraft installed.

### Expected behavior

when I ported form 21 to 22 everything should run fine
### Actual behavior

the command works interrupts the program that is running and terminates it
### Steps to reproduce

while true do peripheral.call(StargateSIDE,"openIris") sleep(1) peripheral.call(StargateSIDE,"closeIris") sleep(1)  end
 or the reverse

and disengage is also acting weird

### System information

- MinecraftForge version: *10.13.4.1614*
- LanteaCraft version: *LC2-22*
- Logs: *include any links to your log files here*

**Comment by AfterLifeLochie** [comment]
You should wrap calls to Stargate peripheral calls (`peripheral.call`, `wrappedPeripheral.openIris`, etc) in error handlers, since the Stargate will throw an error if something is wrong. Generally speaking this will be some descriptive useful text.

(You can read about exception handling at http://www.lua.org/manual/5.1/manual.html#2.7)

**Comment by lieven121** [comment]
![2016-11-21_21 12 30](https://cloud.githubusercontent.com/assets/7773244/20498919/5acc6aa6-b02f-11e6-9063-195425e2b26c.png)

I tested it like you said but still the same and no error

**Comment by AfterLifeLochie** [comment]
Can you provide copies of the server log and the LanteaCraft log files?

**Comment by AfterLifeLochie** [comment]
After re-testing this in a special build using pcall:

![](http://puu.sh/suLNP/21065e71f6.png)

You can see that `ok` is `false` so an error is occuring in the call (even though it's executing the action). This is the info I needed. 🔢

**Comment by AfterLifeLochie** [comment]
Resolved in dfad15fb2d962f4b07182616f0a3140ca02da115:

![](http://puu.sh/suMbs/dab3781b5d.png)

**Comment by lieven121** [comment]
thx 
and sorry for not giving log files / checking this myself I have been busy the last few days 
but I am happy you found it

**Comment by AfterLifeLochie** [comment]
No problem. In the event that you can't get computer methods to work and need to open a bug report, use the script I used above (obviously, you can do a more pretty print version if you want; I've shrunk out the spaces to make it fit).
