### ISSUE TITLE
Server Crashed 29 times since it started from this - 

### ISSUE THREAD

**Issue by ProsperCraft** [PC-Logix/LanteaCraft#452]
### Submission checklist

- [X ] Check that you are running the latest recommended version of LanteaCraft.
- [ X] Check that the issue isn't a known problem already (https://github.com/PC-Logix/LanteaCraft/issues).
- [ ] Check that you can repeat this issue with just LanteaCraft installed.

### Actual behavior

Server Crashes

### Steps to reproduce

Random

### System information

- MinecraftForge version: 1614
- LanteaCraft version: LanteaCraft{1.0.0-22} [LanteaCraft] (LanteaCraft-1.7.10-22.jar) 
- Logs: https://gist.github.com/ProsperCraft/038419ee181042afa9a98141bbf03304 - With Thermos
And 28 more times in one night.
and https://gist.github.com/ProsperCraft/9a1b9f5cd7a61415274edd59fc081df7 - Forge only back in Dec.

Someone else with the same crash different mods - http://www.minecraftforum.net/forums/support/server-support/2742578-extremely-strange-server-crash

**Comment by CaitlynMainer** [comment]
This looks exactly like #442

**Comment by AfterLifeLochie** [comment]
I'm sure e363a4fd014bd765e8bec61ab09f490fdddb4dfb should be in LC2-22?

**Comment by CaitlynMainer** [comment]
22 was ran on November 13th, that commit was done the 19th.  I can run another build though

**Comment by CaitlynMainer** [comment]
build 23 has this change, and more.

**Comment by mRichard629** [comment]
I really appreciate that you guys are still working on this.
