### ISSUE TITLE
Crashes immediately once output log starts up.

### ISSUE THREAD

**Issue by Devilswarchild** [PC-Logix/LanteaCraft#453]
Mc version 1.11.2
Forge version - 13.20.0.2308
LanteaCraft Build Version 1.7.10-23
[2017-05-29-7.log.gz](https://github.com/PC-Logix/LanteaCraft/files/1036716/2017-05-29-7.log.gz)

[fml-client-latest.zip](https://github.com/PC-Logix/LanteaCraft/files/1036717/fml-client-latest.zip)

crashes immediately upon output log generation

**Comment by CaitlynMainer** [comment]
Umm.. we don't have a 1.11 build. Lanteacraft is a 1.7.10 mod.
Note the version "1.7.10-23"
