### ISSUE TITLE
Where is the 1.10.2 download ? Link doesn't work ?

### ISSUE THREAD

**Issue by craig1988** [PC-Logix/LanteaCraft#454]
*Thank you for reporting an issue with LanteaCraft. Please fill out this template when submitting your report - thank you!*

### Submission checklist

- [ ] Check that you are running the latest recommended version of LanteaCraft.
- [ ] Check that the issue isn't a known problem already (https://github.com/PC-Logix/LanteaCraft/issues).
- [ ] Check that you can repeat this issue with just LanteaCraft installed.

### Expected behavior

*Write your expected behavior here.*

### Actual behavior

*Write what you have observed here.*

### Steps to reproduce

*Write any steps you have taken to reproduce the issue here.*

### System information

- MinecraftForge version: *write your version here*
- LanteaCraft version: *write your version here*
- Logs: *include any links to your log files here*

**Comment by CaitlynMainer** [comment]
What are you talking about? There is no 1.10 download, we don't advertise a 1.10 download anywhere.  Lanteacraft is a 1.7.10 mod.

**Comment by craig1988** [comment]
Sorry I saw something on the twitter ? Are there plans for 1.10.2

**Comment by CaitlynMainer** [comment]
Not at this time.

**Comment by craig1988** [comment]
No prob thanks for the speedy reply I wish you well
