### ISSUE TITLE
Doors not displayed properly

### ISSUE THREAD

**Issue by joneschrisan** [PC-Logix/LanteaCraft#458]
*Thank you for reporting an issue with LanteaCraft. Please fill out this template when submitting your report - thank you!*

### Submission checklist

- [Y] Check that you are running the latest recommended version of LanteaCraft.
- [Y] Check that the issue isn't a known problem already (https://github.com/PC-Logix/LanteaCraft/issues).
- [Y] Check that you can repeat this issue with just LanteaCraft installed.

### Expected behavior

Place a door and is should be full height, 2 blocks high i believe for both doors.

### Actual behavior

Door is half height, the top half only

### Steps to reproduce

Place a door, it's only half height, the top half only. removing the block under the door does not reveal the bottom half of the door.

### System information

- MinecraftForge version: Minecraft: 1.7.10; Forge 10.13.4.1558
- LanteaCraft version: 1.7.10-23
- Logs: 

Server output when door placed:
None

**Comment by AfterLifeLochie** [comment]
The doors were modified to only be one unit high, in order for them to be built in whatever arrangement you like (vertically & horizontally, along the same opening plane), including reversing the direction of opening. They'll still (or should) still trigger as one consistent door (including redstone control).
