### ISSUE TITLE
I built two stargate portals and It worked but it wouldn't let me go back on the one I just came threw.

### ISSUE THREAD

**Issue by acarr727** [PC-Logix/LanteaCraft#464]
*Thank you for reporting an issue with LanteaCraft. Please fill out this template when submitting your report - thank you!*

### Submission checklist

- [x] Check that you are running the latest recommended version of LanteaCraft.
- [x] Check that the issue isn't a known problem already (https://github.com/PC-Logix/LanteaCraft/issues).
- [x] Check that you can repeat this issue with just LanteaCraft installed.

### Expected behavior

*Write your expected behavior here.*

### Actual behavior

*Write what you have observed here.*

### Steps to reproduce

*Write any steps you have taken to reproduce the issue here.*

### System information

- MinecraftForge version: *write your version here*
- LanteaCraft version: *write your version here*
- Logs: *include any links to your log files here*

**Comment by lieven121** [comment]
This is not a really a bug currently there is now way to enable two-way travel
but this isn't cannon
in the series (as far as i kown) matter only goes in one way

**Comment by CaitlynMainer** [comment]
As lieven121 said, this is not a bug, in earlier versions of LanteaCraft there was a config option for 2 way travel, but this isn't planned for LC2.
