### ISSUE TITLE
Idea how to change address system

### ISSUE THREAD

**Issue by hunator** [PC-Logix/LanteaCraft#48]
How can be seen, when address was changed to 9 chevron, number of same characters has grown. Easy hack would be to change radix to be dependent on place in address string (line 120 in GateAddressHelper file).

But I would rather suggest to change address system completely.
I would suggest to make file in save DIR (maybe CSV) with dimension, x, y, z and address.
When would stargate be build/loaded it will search file for its coordinates, if there will be a match it will just load its address. If there won't be one it will generate random address one character at time. If char will be occupied it will simply generates new one, so it wouldn't be possible to have address with same char (at least in one dimension).

I would also suggest to generate this way just first six symbols. For the 8 or 9 symbol long address I would suggest dimension number + gate system. So every world dimension would have corresponding 3 symbols (milky way, pegasus and destiny - I know that you are planning others but if you really need them you can add them in corresponding galaxy system like tollan gate in SG1). For less distant dimensions it can use 8 symbol long address, for more distant one 9 (different page), same dimension 7.
So gate address would look like:
RRRRRRO
RRRRRRDO
RRRRRRDDO (saved in file)
(R-originally random, could be rewritten in file; D-dimension; O-point of origin)
For point of origin I would suggest to using special symbol known to be gate specific (in series there are only 3 known - giza A, original earth looks like capital omega, abidos 'A') so randomly choose one of them with probability 1/39 for first two.

It would have few pos.:
- More accurate to series
- User defined addresses possibility
- Possibility to address infinite world
- No restriction of minimal distance (just 2,349,088,560 gates in one dimension)
- Usage of X, Y, Z coordinates instead of X, Z
- Eliminating of those ugly addresses

Some cons. too:
- Need of some file with addresses (checking if it is still valid)
- Some coding
- Would brake current addresses (but it is still RC right?)
- This wouldn't be accurate to SGU because it uses different system (relative addresses instead of absolute) but it could be resolve later on

Please note: I would post patch if I can but I can't (I can't program in java and I'm not minecraft moder). So this idea could be the dummiest / craziest thing in the world. Because I don't simply know how it works (I've just studied part of your source).

**Comment by AfterLifeLochie** [comment]
Fast-forward; added in 2.0-rewrite-initial.
